# CSE 151B Competition — Starter Notebook

Welcome to the **CSE 151B Spring 2026 Math Reasoning Competition**!  
This notebook walks you through the full pipeline end-to-end:

1. Setting up the Python environment with `uv`
2. Loading the competition dataset
3. Running inference with **Qwen3-4B-Thinking** via vLLM (INT8 quantized)
4. Scoring responses against ground-truth answers
5. Saving results to JSONL for submission

The public dataset (`public.jsonl`) contains questions **with** answers so you can measure accuracy locally.  
The private test set used for the leaderboard does **not** include answers — for that, skip evaluation and submit the raw responses.

## 1. Environment Setup

We use [`uv`](https://github.com/astral-sh/uv) for fast, reproducible package management.

The steps below:
1. Install `uv` into `~/.local/bin`
2. Create a virtual environment at `.venv/`
3. Install all required packages (This might take a while)

> **After running this cell, restart the kernel** so that the newly installed packages (especially `vllm` and `transformers`) are picked up by the current Python session.

### Comment Out the cell below after first installation.

In [ ]:
# # Install uv
# !wget -qO- https://astral.sh/uv/install.sh | sh

# # Create a virtual environment
# !uv venv .venv --python python3.13 --seed --clear

# # Install dependencies — this is fast thanks to uv's parallel resolver
# !.venv/bin/python -m pip install sympy numpy transformers vllm tqdm bitsandbytes antlr4-python3-runtime==4.11.1 ipykernel jupyter accelerate>=0.26.0

# # Install Jupyter Kernel
# !.venv/bin/python -m ipykernel install --user --name cse151b --display-name "Python (cse151b)"

# print("Done. Restart the kernel before proceeding.")
# print("Selection process: on top right, click on current kernel '(ususally named python)' -> 'select another kernel' -> 'Jupyter Kernel' -> 'Python (cse151b)'.")

downloading uv 0.11.7 x86_64-unknown-linux-gnu
installing to /home/potato/.local/bin
  uv
  uvx
everything's installed!
Using CPython 3.13.13
Creating virtual environment with seed packages at: .venv
 + pip==26.0.1
Activate with: source .venv/bin/activate
Installed kernelspec cse151b in /home/potato/.local/share/jupyter/kernels/cse151b
Done. Restart the kernel before proceeding.
Selection process: on top right, click on current kernel '(ususally named python)' -> 'select another kernel' -> 'Jupyter Kernel' -> 'Python (cse151b)'.

In [2]:
#must install trl first
import sys
!{sys.executable} -m pip install trl

Requirement already satisfied: trl in ./.venv/lib/python3.13/site-packages (1.5.1)
Requirement already satisfied: accelerate>=1.4.0 in ./.venv/lib/python3.13/site-packages (from trl) (1.13.0)
Requirement already satisfied: datasets>=4.7.0 in ./.venv/lib/python3.13/site-packages (from trl) (4.8.5)
Requirement already satisfied: jinja2 in ./.venv/lib/python3.13/site-packages (from trl) (3.1.6)
Requirement already satisfied: packaging>20.0 in ./.venv/lib/python3.13/site-packages (from trl) (26.2)
Requirement already satisfied: transformers>=4.56.2 in ./.venv/lib/python3.13/site-packages (from trl) (5.9.0)
Requirement already satisfied: numpy>=1.17 in ./.venv/lib/python3.13/site-packages (from accelerate>=1.4.0->trl) (2.4.6)
Requirement already satisfied: psutil in ./.venv/lib/python3.13/site-packages (from accelerate>=1.4.0->trl) (7.2.2)
Requirement already satisfied: pyyaml in ./.venv/lib/python3.13/site-packages (from accelerate>=1.4.0->trl) (6.0.3)
Requirement already satisfied: torch>=2.0.0 in ./.venv/lib/python3.13/site-packages (from accelerate>=1.4.0->trl) (2.11.0)
Requirement already satisfied: huggingface_hub>=0.21.0 in ./.venv/lib/python3.13/site-packages (from accelerate>=1.4.0->trl) (1.17.0)
Requirement already satisfied: safetensors>=0.4.3 in ./.venv/lib/python3.13/site-packages (from accelerate>=1.4.0->trl) (0.7.0)
Requirement already satisfied: filelock in ./.venv/lib/python3.13/site-packages (from datasets>=4.7.0->trl) (3.29.0)
Requirement already satisfied: pyarrow>=21.0.0 in ./.venv/lib/python3.13/site-packages (from datasets>=4.7.0->trl) (24.0.0)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in ./.venv/lib/python3.13/site-packages (from datasets>=4.7.0->trl) (0.4.1)
Requirement already satisfied: pandas in ./.venv/lib/python3.13/site-packages (from datasets>=4.7.0->trl) (3.0.3)
Requirement already satisfied: requests>=2.32.2 in ./.venv/lib/python3.13/site-packages (from datasets>=4.7.0->trl) (2.34.2)
Requirement already satisfied: httpx<1.0.0 in ./.venv/lib/python3.13/site-packages (from datasets>=4.7.0->trl) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in ./.venv/lib/python3.13/site-packages (from datasets>=4.7.0->trl) (4.67.3)
Requirement already satisfied: xxhash in ./.venv/lib/python3.13/site-packages (from datasets>=4.7.0->trl) (3.7.0)
Requirement already satisfied: multiprocess<0.70.20 in ./.venv/lib/python3.13/site-packages (from datasets>=4.7.0->trl) (0.70.19)
Requirement already satisfied: fsspec<=2026.2.0,>=2023.1.0 in ./.venv/lib/python3.13/site-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets>=4.7.0->trl) (2026.2.0)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in ./.venv/lib/python3.13/site-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets>=4.7.0->trl) (3.13.5)
Requirement already satisfied: anyio in ./.venv/lib/python3.13/site-packages (from httpx<1.0.0->datasets>=4.7.0->trl) (4.13.0)
Requirement already satisfied: certifi in ./.venv/lib/python3.13/site-packages (from httpx<1.0.0->datasets>=4.7.0->trl) (2026.5.20)
Requirement already satisfied: httpcore==1.* in ./.venv/lib/python3.13/site-packages (from httpx<1.0.0->datasets>=4.7.0->trl) (1.0.9)
Requirement already satisfied: idna in ./.venv/lib/python3.13/site-packages (from httpx<1.0.0->datasets>=4.7.0->trl) (3.17)
Requirement already satisfied: h11>=0.16 in ./.venv/lib/python3.13/site-packages (from httpcore==1.*->httpx<1.0.0->datasets>=4.7.0->trl) (0.16.0)
Requirement already satisfied: click>=8.4.0 in ./.venv/lib/python3.13/site-packages (from huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (8.4.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in ./.venv/lib/python3.13/site-packages (from huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (1.5.0)
Requirement already satisfied: typer<0.26.0,>=0.20.0 in ./.venv/lib/python3.13/site-packages (from huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (0.25.1)
Requirement already satisfied: typing-extensions>=4.1.0 in ./.venv/lib/python3.13/site-packages (from huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (4.15.0)
Requirement already satisfied: shellingham>=1.3.0 in ./.venv/lib/python3.13/site-packages (from typer<0.26.0,>=0.20.0->huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in ./.venv/lib/python3.13/site-packages (from typer<0.26.0,>=0.20.0->huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (15.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in ./.venv/lib/python3.13/site-packages (from typer<0.26.0,>=0.20.0->huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (0.0.4)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in ./.venv/lib/python3.13/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets>=4.7.0->trl) (2.6.2)
Requirement already satisfied: aiosignal>=1.4.0 in ./.venv/lib/python3.13/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets>=4.7.0->trl) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in ./.venv/lib/python3.13/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets>=4.7.0->trl) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in ./.venv/lib/python3.13/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets>=4.7.0->trl) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in ./.venv/lib/python3.13/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets>=4.7.0->trl) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in ./.venv/lib/python3.13/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets>=4.7.0->trl) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in ./.venv/lib/python3.13/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets>=4.7.0->trl) (1.24.2)
Requirement already satisfied: charset_normalizer<4,>=2 in ./.venv/lib/python3.13/site-packages (from requests>=2.32.2->datasets>=4.7.0->trl) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.26 in ./.venv/lib/python3.13/site-packages (from requests>=2.32.2->datasets>=4.7.0->trl) (2.7.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in ./.venv/lib/python3.13/site-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in ./.venv/lib/python3.13/site-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in ./.venv/lib/python3.13/site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (0.1.2)
Requirement already satisfied: setuptools<82 in ./.venv/lib/python3.13/site-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (80.10.2)
Requirement already satisfied: sympy>=1.13.3 in ./.venv/lib/python3.13/site-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in ./.venv/lib/python3.13/site-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (3.6.1)
Requirement already satisfied: cuda-toolkit==13.0.2 in ./.venv/lib/python3.13/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (13.0.2)
Requirement already satisfied: cuda-bindings<14,>=13.0.3 in ./.venv/lib/python3.13/site-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (13.3.1)
Requirement already satisfied: nvidia-cudnn-cu13==9.19.0.56 in ./.venv/lib/python3.13/site-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu13==0.8.0 in ./.venv/lib/python3.13/site-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (0.8.0)
Requirement already satisfied: nvidia-nccl-cu13==2.28.9 in ./.venv/lib/python3.13/site-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu13==3.4.5 in ./.venv/lib/python3.13/site-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (3.4.5)
Requirement already satisfied: triton==3.6.0 in ./.venv/lib/python3.13/site-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (3.6.0)
Requirement already satisfied: nvidia-cublas==13.1.0.3.* in ./.venv/lib/python3.13/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (13.1.0.3)
Requirement already satisfied: nvidia-cuda-runtime==13.0.96.* in ./.venv/lib/python3.13/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (13.0.96)
Requirement already satisfied: nvidia-cufft==12.0.0.61.* in ./.venv/lib/python3.13/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (12.0.0.61)
Requirement already satisfied: nvidia-cufile==1.15.1.6.* in ./.venv/lib/python3.13/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (1.15.1.6)
Requirement already satisfied: nvidia-cuda-cupti==13.0.85.* in ./.venv/lib/python3.13/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (13.0.85)
Requirement already satisfied: nvidia-curand==10.4.0.35.* in ./.venv/lib/python3.13/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (10.4.0.35)
Requirement already satisfied: nvidia-cusolver==12.0.4.66.* in ./.venv/lib/python3.13/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (12.0.4.66)
Requirement already satisfied: nvidia-cusparse==12.6.3.3.* in ./.venv/lib/python3.13/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (12.6.3.3)
Requirement already satisfied: nvidia-nvjitlink==13.0.88.* in ./.venv/lib/python3.13/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (13.0.88)
Requirement already satisfied: nvidia-cuda-nvrtc==13.0.88.* in ./.venv/lib/python3.13/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (13.0.88)
Requirement already satisfied: nvidia-nvtx==13.0.85.* in ./.venv/lib/python3.13/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (13.0.85)
Requirement already satisfied: cuda-pathfinder>=1.4.2 in ./.venv/lib/python3.13/site-packages (from cuda-bindings<14,>=13.0.3->torch>=2.0.0->accelerate>=1.4.0->trl) (1.5.5)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in ./.venv/lib/python3.13/site-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate>=1.4.0->trl) (1.3.0)
Requirement already satisfied: regex>=2025.10.22 in ./.venv/lib/python3.13/site-packages (from transformers>=4.56.2->trl) (2026.5.9)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in ./.venv/lib/python3.13/site-packages (from transformers>=4.56.2->trl) (0.22.2)
Requirement already satisfied: MarkupSafe>=2.0 in ./.venv/lib/python3.13/site-packages (from jinja2->trl) (3.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.13/site-packages (from pandas->datasets>=4.7.0->trl) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas->datasets>=4.7.0->trl) (1.17.0)

In [1]:
from trl import GRPOTrainer, GRPOConfig
print("GRPO installation successful!")

/workspace/151B_SP26_Competition/.venv/lib/python3.13/site-packages/trl/generation/__init__.py:22: UserWarning: TRL currently supports vLLM versions from 0.12.0 to 0.18.0. You have version 0.22.0 installed. We recommend installing a supported version to avoid compatibility issues.
  if is_vllm_available():
/workspace/151B_SP26_Competition/.venv/lib/python3.13/site-packages/trl/generation/vllm_client.py:40: UserWarning: TRL currently supports vLLM versions from 0.12.0 to 0.18.0. You have version 0.22.0 installed. We recommend installing a supported version to avoid compatibility issues.
  if is_vllm_available():
/workspace/151B_SP26_Competition/.venv/lib/python3.13/site-packages/trl/generation/vllm_generation.py:41: UserWarning: TRL currently supports vLLM versions from 0.12.0 to 0.18.0. You have version 0.22.0 installed. We recommend installing a supported version to avoid compatibility issues.
  if is_vllm_available():

GRPO installation successful!

### Run the cell below every time to activate the installed environment.

In [2]:
# activate venv after installation. This needs to be run everytime.
!.venv/bin/python -m ipykernel install --user --name cse151b --display-name "Python (cse151b)"

!source ./.venv/bin/activate

Installed kernelspec cse151b in /root/.local/share/jupyter/kernels/cse151b

## 2. Imports & Configuration

All key settings are collected in one place.  
- `DATA_PATH` — public dataset with ground-truth answers (use this to measure accuracy)
- `OUTPUT_PATH` — where per-question results will be written
- `GPU_ID` — which GPU to use (update if your machine has a different device index)
- `MAX_TOKENS` — maximum tokens the model may generate per response

In [3]:
import os
os.environ["PYTORCH_ALLOC_CONF"] = "expandable_segments:True"
import torch

print("CUDA Available:", torch.cuda.is_available())
print("CUDA Device Count:", torch.cuda.device_count())

if torch.cuda.is_available():
    for i in range(torch.cuda.device_count()):
        print(f"GPU {i}: {torch.cuda.get_device_name(i)}")
        print(f"  Memory: {torch.cuda.get_device_properties(i).total_memory / 1024**3:.2f} GB")
else:
    print("\n⚠️  No CUDA GPUs detected!")
    print("Check your CUDA installation or install PyTorch with CUDA support:")
    print("pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118")

CUDA Available: True
CUDA Device Count: 1
GPU 0: NVIDIA L40S
  Memory: 44.39 GB

In [4]:
import json
import os
import re
import sys
from pathlib import Path
from typing import Optional

from transformers import AutoTokenizer
from vllm import LLM, SamplingParams
from tqdm import tqdm

# ── Configuration ─────────────────────────────────────────────────────────────
MODEL_ID    = "Qwen/Qwen3-4B-Thinking-2507"
GPU_ID      = "0"                    # CUDA_VISIBLE_DEVICES
DATA_PATH   = "data/public.jsonl"
OUTPUT_PATH = "results/starter_results.jsonl"
MAX_TOKENS  = 32768 #32768

os.environ["CUDA_VISIBLE_DEVICES"] = GPU_ID

## 3. Load the Dataset

The dataset is stored as newline-delimited JSON (`.jsonl`). Each line is one question with the following fields:

| Field | Description |
|---|---|
| `id` | Unique question identifier |
| `question` | Problem statement |
| `options` | List of answer choices — present for **MCQ**, absent for **free-form** |
| `answer` | Ground-truth answer (letter for MCQ, value/list for free-form) |

In [5]:
data = [json.loads(line) for line in open(DATA_PATH)]

n_mcq  = sum(bool(d.get("options")) for d in data)
n_free = sum(not d.get("options")   for d in data)
print(f"Loaded {len(data)} questions  ({n_mcq} MCQ, {n_free} free-form)")

# Preview one MCQ and one free-form item
mcq_sample  = next(d for d in data if d.get("options"))
free_sample = next(d for d in data if not d.get("options"))

print("\n── MCQ sample ──")
print(json.dumps(mcq_sample, indent=2))
print("\n── Free-form sample ──")
print(json.dumps(free_sample, indent=2))

Loaded 1126 questions  (375 MCQ, 751 free-form)

── MCQ sample ──
{
  "question": "$int_{-infty}^{+infty} frac{a^{3/2}}{s^2+a^2} ds = $",
  "options": [
    "$0$",
    "$frac{1}{a}$",
    "$frac{3}{a}$",
    "$frac{1}{2a^2}$",
    "$frac{1}{2a}$",
    "$frac{2}{a}$",
    "$2a$",
    "$frac{3}{2a}$",
    "$frac{3}{2a^2}$",
    "$frac{1}{a^2}$"
  ],
  "answer": "F",
  "id": 1
}

── Free-form sample ──
{
  "question": "Find the sum of the first $325$ positive even whole numbers. Sum: [ANS]",
  "answer": [
    "325*(1+325)"
  ],
  "id": 0
}

## 4. Prompt Construction

We use two system prompts depending on the question type:

- **MCQ** — the model must select the best answer letter and wrap it in `\boxed{}`
- **Free-form** — the model solves step-by-step and puts the final answer in `\boxed{}`

`build_prompt()` returns the appropriate `(system, user)` pair for each item.

In [6]:
SYSTEM_PROMPT_MATH = (
    "You are an expert mathematician. "
    "Think freely and explore multiple approaches before committing to one. "
    "If you realize you made an error, correct it immediately and try a different approach. "
    "Always use Chinese for your reasoning and thought process, but your final answer must be in English. "
    "Put your final answer inside \\boxed{}. "
    "If the problem has multiple sub-answers, separate them by commas inside a single \\boxed{}, "
    "e.g. \\boxed{3, 7}."
)

SYSTEM_PROMPT_MCQ = (
    "You are an expert mathematician. Solve the problem step-by-step. "
    "Please always use Chinese for your reasoning and thought process, but your final answer has to be in English, and it needs to be clear and accurate. "
    "Read the problem and the answer choices below, then select the single best answer. "
    "Output ONLY the letter of your chosen option inside \\boxed{}, e.g. \\boxed{C}."
)

# Add this to your prompt builder to suppress the <think> block
SYSTEM_PROMPT_MCQ_SHORT = (
    "Solve the problem. "
    "Reply with ONLY the answer letter inside \\boxed{}, e.g. \\boxed{A}. "
    "No explanation."
)

SYSTEM_PROMPT_MATH_SHORT = (
    "Solve the problem. "
    "Reply with ONLY the final answer inside \\boxed{}, e.g. \\boxed{42}. "
    "No explanation."
)

In [7]:
def build_prompt(question: str, options: Optional[list]) -> tuple[str, str]:
    """Return (system_prompt, user_prompt) for a question."""
    if options:
        labels    = [chr(65 + i) for i in range(len(options))]
        opts_text = "\n".join(f"{lbl}. {opt.strip()}" for lbl, opt in zip(labels, options))
        return SYSTEM_PROMPT_MCQ, f"{question}\n\nOptions:\n{opts_text}"
    return SYSTEM_PROMPT_MATH, question


# Verify with samples
for label, item in [("MCQ", mcq_sample), ("Free-form", free_sample)]:
    sys_p, usr_p = build_prompt(item["question"], item.get("options"))
    print(f"── {label} user prompt (first 200 chars) ──")
    print(usr_p[:200], "...\n")

── MCQ user prompt (first 200 chars) ──
$int_{-infty}^{+infty} frac{a^{3/2}}{s^2+a^2} ds = $

Options:
A. $0$
B. $frac{1}{a}$
C. $frac{3}{a}$
D. $frac{1}{2a^2}$
E. $frac{1}{2a}$
F. $frac{2}{a}$
G. $2a$
H. $frac{3}{2a}$
I. $frac{3}{2a^2}$
J. ...

── Free-form user prompt (first 200 chars) ──
Find the sum of the first $325$ positive even whole numbers. Sum: [ANS] ...

## 5. Load Model with vLLM

We load **Qwen3-4B-Thinking-2507** with **INT8 quantization** via BitsAndBytes.  
Setting `load_format="bitsandbytes"` tells vLLM to apply on-the-fly INT8 weight quantization, roughly halving GPU memory usage compared to BF16.

Key parameters:
- `gpu_memory_utilization` — fraction of GPU VRAM reserved for the model and KV cache
- `max_model_len` — maximum sequence length (prompt + generation)
- `max_num_seqs` — maximum number of sequences processed in parallel

In [8]:
tokenizer = AutoTokenizer.from_pretrained(MODEL_ID, use_fast=True)
tokenizer.pad_token = tokenizer.eos_token

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [ ]:
llm = LLM(
    model=MODEL_ID,
    quantization="bitsandbytes",
    load_format="bitsandbytes",
    enable_prefix_caching=False,
    gpu_memory_utilization=0.85,
    max_model_len=6240,
    trust_remote_code=True,
    max_num_seqs=256,
    max_num_batched_tokens=32768,
    enable_lora=True,
    max_lora_rank=64,
)

print("Model loaded.")

INFO 05-12 00:44:49 [utils.py:233] non-default args: {'trust_remote_code': True, 'load_format': 'bitsandbytes', 'max_model_len': 6240, 'enable_prefix_caching': False, 'gpu_memory_utilization': 0.85, 'max_num_batched_tokens': 32768, 'max_num_seqs': 256, 'disable_log_stats': True, 'quantization': 'bitsandbytes', 'enable_lora': True, 'max_lora_rank': 64, 'model': 'Qwen/Qwen3-4B-Thinking-2507'}
INFO 05-12 00:44:50 [model.py:549] Resolved architecture: Qwen3ForCausalLM
INFO 05-12 00:44:50 [model.py:1678] Using max model len 6240
INFO 05-12 00:44:50 [scheduler.py:238] Chunked prefill is enabled with max_num_batched_tokens=32768.
INFO 05-12 00:44:52 [vllm.py:790] Asynchronous scheduling is enabled.
WARNING 05-12 00:44:53 [system_utils.py:152] We must use the `spawn` multiprocessing start method. Overriding VLLM_WORKER_MULTIPROC_METHOD to 'spawn'. See https://docs.vllm.ai/en/latest/usage/troubleshooting.html#python-multiprocessing for more information. Reasons: CUDA is initialized
(EngineCore pid=74935) INFO 05-12 00:45:02 [core.py:105] Initializing a V1 LLM engine (v0.19.0) with config: model='Qwen/Qwen3-4B-Thinking-2507', speculative_config=None, tokenizer='Qwen/Qwen3-4B-Thinking-2507', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.bfloat16, max_seq_len=6240, download_dir=None, load_format=bitsandbytes, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=False, quantization=bitsandbytes, enforce_eager=False, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=Qwen/Qwen3-4B-Thinking-2507, enable_prefix_caching=False, enable_chunked_prefill=True, pooler_config=None, compilation_config={'mode': <CompilationMode.VLLM_COMPILE: 3>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['none'], 'splitting_ops': ['vllm::unified_attention', 'vllm::unified_attention_with_output', 'vllm::unified_mla_attention', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::linear_attention', 'vllm::plamo2_mamba_mixer', 'vllm::gdn_attention_core', 'vllm::olmo_hybrid_gdn_full_forward', 'vllm::kda_attention', 'vllm::sparse_attn_indexer', 'vllm::rocm_aiter_sparse_attn_indexer', 'vllm::unified_kv_cache_update', 'vllm::unified_mla_kv_cache_update'], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_images_per_batch': 0, 'compile_sizes': [], 'compile_ranges_endpoints': [32768], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [1, 2, 4, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256, 272, 288, 304, 320, 336, 352, 368, 384, 400, 416, 432, 448, 464, 480, 496, 512], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': False, 'fuse_act_quant': False, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False}, 'max_cudagraph_capture_size': 512, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': True, 'static_all_moe_layers': []}
(EngineCore pid=74935) INFO 05-12 00:45:03 [parallel_state.py:1400] world_size=1 rank=0 local_rank=0 distributed_init_method=tcp://192.168.1.170:36217 backend=nccl
(EngineCore pid=74935) INFO 05-12 00:45:03 [parallel_state.py:1716] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, PCP rank 0, TP rank 0, EP rank N/A, EPLB rank N/A
(EngineCore pid=74935) INFO 05-12 00:45:03 [gpu_model_runner.py:4735] Starting to load model Qwen/Qwen3-4B-Thinking-2507...
(EngineCore pid=74935) INFO 05-12 00:45:05 [cuda.py:334] Using FLASH_ATTN attention backend out of potential backends: ['FLASH_ATTN', 'FLASHINFER', 'TRITON_ATTN', 'FLEX_ATTENTION'].
(EngineCore pid=74935) INFO 05-12 00:45:05 [flash_attn.py:596] Using FlashAttention version 2

(EngineCore pid=74935) <frozen importlib._bootstrap_external>:1325: FutureWarning: The cuda.cudart module is deprecated and will be removed in a future release, please switch to use the cuda.bindings.runtime module instead.
(EngineCore pid=74935) <frozen importlib._bootstrap_external>:1325: FutureWarning: The cuda.nvrtc module is deprecated and will be removed in a future release, please switch to use the cuda.bindings.nvrtc module instead.

(EngineCore pid=74935) INFO 05-12 00:45:05 [bitsandbytes_loader.py:786] Loading weights with BitsAndBytes quantization. May take a while ...

Loading safetensors checkpoint shards:   0% Completed | 0/3 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:  33% Completed | 1/3 [00:03<00:06,  3.43s/it]
Loading safetensors checkpoint shards:  67% Completed | 2/3 [00:06<00:03,  3.48s/it]
Loading safetensors checkpoint shards: 100% Completed | 3/3 [00:07<00:00,  2.01s/it]
Loading safetensors checkpoint shards: 100% Completed | 3/3 [00:07<00:00,  2.40s/it]
(EngineCore pid=74935)

(EngineCore pid=74935) INFO 05-12 00:45:13 [punica_selector.py:20] Using PunicaWrapperGPU.
(EngineCore pid=74935) INFO 05-12 00:45:14 [gpu_model_runner.py:4820] Model loading took 2.99 GiB memory and 9.375992 seconds
(EngineCore pid=74935) INFO 05-12 00:45:25 [backends.py:1051] Using cache directory: /home/arihant/.cache/vllm/torch_compile_cache/47ad7e722d/rank_0_0/backbone for vLLM's torch.compile
(EngineCore pid=74935) INFO 05-12 00:45:25 [backends.py:1111] Dynamo bytecode transform time: 10.99 s
(EngineCore pid=74935) INFO 05-12 00:45:26 [backends.py:372] Cache the graph of compile range (1, 32768) for later use
(EngineCore pid=74935) INFO 05-12 00:45:27 [backends.py:390] Compiling a graph for compile range (1, 32768) takes 1.45 s
(EngineCore pid=74935) INFO 05-12 00:45:30 [decorators.py:640] saved AOT compiled function to /home/arihant/.cache/vllm/torch_compile_cache/torch_aot_compile/59324795658b558999a567332ec6aabac18b01a87e8b72f71a2bd7f8946ab87f/rank_0_0/model
(EngineCore pid=74935) INFO 05-12 00:45:30 [monitor.py:48] torch.compile took 15.97 s in total
(EngineCore pid=74935) INFO 05-12 00:45:31 [monitor.py:76] Initial profiling/warmup run took 0.34 s
(EngineCore pid=74935) INFO 05-12 00:45:41 [kv_cache_utils.py:829] Overriding num_gpu_blocks=0 with num_gpu_blocks_override=512
(EngineCore pid=74935) INFO 05-12 00:45:41 [gpu_model_runner.py:5876] Profiling CUDA graph memory: PIECEWISE=102 (largest=512), FULL=70 (largest=256)
(EngineCore pid=74935) WARNING 05-12 00:45:42 [utils.py:267] Using default LoRA kernel configs
(EngineCore pid=74935) INFO 05-12 00:45:44 [gpu_model_runner.py:5955] Estimated CUDA graph memory: 1.68 GiB total
(EngineCore pid=74935) INFO 05-12 00:45:44 [gpu_worker.py:436] Available KV cache memory: 0.86 GiB
(EngineCore pid=74935) INFO 05-12 00:45:44 [gpu_worker.py:470] In v0.19, CUDA graph memory profiling will be enabled by default (VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=1), which more accurately accounts for CUDA graph memory during KV cache allocation. To try it now, set VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=1 and increase --gpu-memory-utilization from 0.8500 to 1.0000 to maintain the same effective KV cache size.
(EngineCore pid=74935) INFO 05-12 00:45:44 [kv_cache_utils.py:1319] GPU KV cache size: 6,240 tokens
(EngineCore pid=74935) INFO 05-12 00:45:44 [kv_cache_utils.py:1324] Maximum concurrency for 6,240 tokens per request: 1.00x

Capturing CUDA graphs (mixed prefill-decode, PIECEWISE): 100%|██████████| 102/102 [00:20<00:00,  4.89it/s]
Capturing CUDA graphs (decode, FULL): 100%|██████████| 70/70 [00:12<00:00,  5.76it/s]

(EngineCore pid=74935) INFO 05-12 00:46:18 [gpu_model_runner.py:6046] Graph capturing finished in 34 secs, took 2.09 GiB
(EngineCore pid=74935) INFO 05-12 00:46:18 [gpu_worker.py:597] CUDA graph pool memory: 2.09 GiB (actual), 1.68 GiB (estimated), difference: 0.42 GiB (19.9%).
(EngineCore pid=74935) INFO 05-12 00:46:18 [core.py:283] init engine (profile, create kv cache, warmup model) took 64.55 seconds
(EngineCore pid=74935) INFO 05-12 00:46:20 [vllm.py:790] Asynchronous scheduling is enabled.
Model loaded.

In [ ]:
print(llm)

In [8]:
sampling_params = SamplingParams(
    max_tokens=MAX_TOKENS,
    temperature=0.6,
    top_p=0.95,
    top_k=20,
    min_p=0.0,
    presence_penalty=0.0,
    repetition_penalty=1.0,
)

## 6. Generate Responses

We format every question into a chat-template prompt, then call `llm.generate()` in one batched pass.  
vLLM handles batching and scheduling internally — no manual batching needed.

In [ ]:
from vllm.lora.request import LoRARequest

# Build prompts for first 20 entries
prompts = []
for item in data[:20]:
    system, user = build_prompt(item["question"], item.get("options"))
    prompt_text = tokenizer.apply_chat_template(
        [{"role": "system", "content": system},
         {"role": "user",   "content": user}],
        tokenize=False,
        add_generation_prompt=True,
    )
    prompts.append(prompt_text)

# Generate
print(f"Generating responses for {len(prompts)} questions...")
prompts2 = llm.generate(
    prompts, 
    sampling_params=sampling_params,
    lora_request=LoRARequest("grpo_adapter", 1, "./lora_adapters/lora_grpo/lora_grpo",),
    # lora_request=LoRARequest("math_finetune", 1, lora_path="./lora_adapter_comp/lora_adapter_comp"),
    # lora_request=LoRARequest("math_finetune", 1, lora_path="./lora_adapters/lora_adapter_openr1_generate/lora_adapter_openr1_generate"),
)
outputs = llm.generate(
    prompts + prompts2, 
    sampling_params=sampling_params,
    # lora_request=LoRARequest("grpo_adapter", 1, "./lora_adapters/lora_grpo/lora_grpo",),
    # lora_request=LoRARequest("math_finetune", 1, lora_path="./lora_adapter_comp/lora_adapter_comp"),
    lora_request=LoRARequest("math_finetune", 1, lora_path="./lora_adapters/lora_adapter_openr1_generate/lora_adapter_openr1_generate"),
)

responses = [out.outputs[0].text.strip() for out in outputs]

# Preview first 3
for i in range(min(3, len(responses))):
    print(f"\n── Response {i} (id={data[i].get('id')}) ──")
    print(responses[i][400:], "..." if len(responses[i]) > 400 else "")

# # Build prompts for first 5 entries
# prompts = []
# for item in data[:5]:
#     system, user = build_prompt(item["question"], item.get("options"))
#     prompt_text = tokenizer.apply_chat_template(
#         [{"role": "system", "content": system},
#          {"role": "user",   "content": user}],
#         tokenize=False,
#         add_generation_prompt=True,
#     )
#     prompts.append(prompt_text)

# responses = []
# print(f"Generating responses for {len(prompts)} questions...")
# for prompt in prompts:
#     inputs = tokenizer(prompt, return_tensors="pt").to(llm.device)

#     with torch.no_grad():
#         output = llm.generate(
#             **inputs,
#             max_new_tokens=MAX_TOKENS,
#             temperature=0.6,
#             top_p=0.95,
#             top_k=20,
#             do_sample=True,
#             use_cache=True,
#         )

#     text = tokenizer.decode(output[0], skip_special_tokens=True)
#     responses.append(text)
#     print("Responded to a prompt!")

Generating responses for 20 questions...

Rendering prompts:   0%|          | 0/20 [00:00<?, ?it/s]

WARNING 05-12 00:46:20 [input_processor.py:149] vLLM has deprecated support for supporting different tokenizers for different LoRAs. By default, vLLM uses base model's tokenizer. If you are using a LoRA with its own tokenizer, consider specifying `--tokenizer [lora_path]` to use the LoRA tokenizer.

Processed prompts:   0%|          | 0/20 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

── Response 0 (id=0) ──
Okay, let's see. I need to find the sum of the first 325 positive even whole numbers. Hmm, first, let me make sure I understand what the problem is asking. Positive even whole numbers start from 2, right? So the first one is 2, the second is 4, the third is 6, and so on. So we need to sum 2 + 4 + 6 + ... up to the 325th term.

First, I should recall if there's a formula for the sum of an arithmet ...

── Response 1 (id=1) ──
Okay, let's try to solve this integral: the integral from negative infinity to positive infinity of (a^(3/2)) divided by (s² + a²) ds. Hmm, first, I need to check if the integral converges. Since the integrand is even (because s² is even and the denominator is even, so the whole function is even), the integral from -infty to infty is twice the integral from 0 to infty. But maybe it's better to use ...

── Response 2 (id=2) ──
Okay, let's try to solve this problem step by step. First, part (a) is about a turkey cooling down, so I think this is a Newton's Law of Cooling problem. Newton's Law of Cooling states that the rate of change of the temperature of an object is proportional to the difference between its temperature and the ambient temperature. The formula is usually written as:

\( T(t) = T_s + (T_0 - T_s) e^{-kt}  ...

## 7. Score Responses

Scoring differs by question type:

- **MCQ**: extract the predicted letter from `\boxed{}` and compare to the gold letter (exact match).
- **Free-form**: use `Judger.auto_judge()` which handles symbolic and numeric equivalence.

Each result record contains `{id, is_mcq, gold, response, correct}`.

In [10]:
def extract_letter(text: str) -> str:
    m = re.search(r"\\boxed\{([A-Za-z])\}", text)
    if m:
        return m.group(1).upper()
    matches = re.findall(r"\b([A-Z])\b", text.upper())
    return matches[-1] if matches else ""


def score_mcq(response: str, gold_letter: str) -> bool:
    return extract_letter(response) == gold_letter.strip().upper()


# Load Judger for free-form scoring
sys.path.insert(0, ".")
from judger import Judger
judger = Judger(strict_extract=False)

results = []
for item, response in tqdm(zip(data, responses), total=len(data), desc="Scoring"):
    is_mcq = bool(item.get("options"))
    gold   = item["answer"]

    if is_mcq:
        correct = score_mcq(response, str(gold))
    else:
        gold_list = gold if isinstance(gold, list) else [gold]
        try:
            correct = judger.auto_judge(
                pred=response,
                gold=gold_list,
                options=[[]] * len(gold_list),
            )
        except Exception:
            correct = False

    results.append({
        "id":       item.get("id"),
        "is_mcq":   is_mcq,
        "gold":     gold,
        "response": response,
        "correct":  correct,
    })

print(f"Scoring complete. {len(results)} results.")

Scoring:   2%|▏         | 20/1126 [00:00<00:37, 29.53it/s]

Scoring complete. 20 results.

## 8. Summary

Print accuracy broken down by question type.

In [11]:
mcq_res  = [r for r in results if r["is_mcq"]]
free_res = [r for r in results if not r["is_mcq"]]

def acc(subset):
    return sum(r["correct"] for r in subset) / len(subset) * 100 if subset else 0.0

print("=" * 50)
print("EVALUATION RESULTS")
print("=" * 50)
print(f"  MCQ        : {sum(r['correct'] for r in mcq_res):4d} / {len(mcq_res):4d}  ({acc(mcq_res):.2f}%)")
print(f"  Free-form  : {sum(r['correct'] for r in free_res):4d} / {len(free_res):4d}  ({acc(free_res):.2f}%)")
print(f"  Overall    : {sum(r['correct'] for r in results):4d} / {len(results):4d}  ({acc(results):.2f}%)")
print("=" * 50)

==================================================
EVALUATION RESULTS
==================================================
  MCQ        :    2 /    9  (22.22%)
  Free-form  :    6 /   11  (54.55%)
  Overall    :    8 /   20  (40.00%)
==================================================

## 9. Save Results

Results are written as newline-delimited JSON.

**With evaluation** (public set — you have ground-truth):  
Each line: `{id, is_mcq, gold, response, correct}`

**Without evaluation** (private test set — no ground-truth available):  
Each line: `{id, is_mcq, response}` — omit `gold` and `correct`.

Toggle `SAVE_EVAL` below accordingly.

In [12]:
SAVE_EVAL = True   # Set to False when running on the private test set

out_path = Path(OUTPUT_PATH)
out_path.parent.mkdir(parents=True, exist_ok=True)

with open(out_path, "w") as f:
    for r in results:
        if SAVE_EVAL:
            record = {"id": r["id"], "is_mcq": r["is_mcq"], "gold": r["gold"],
                      "response": r["response"], "correct": r["correct"]}
        else:
            record = {"id": r["id"], "is_mcq": r["is_mcq"], "response": r["response"]}
        f.write(json.dumps(record) + "\n")

print(f"Saved {len(results)} records to {out_path}")

Saved 20 records to results/starter_results.jsonl

## Next Steps

This notebook gives you a working baseline. Here are directions to improve your score:

- **Prompt engineering** — try different system prompts or few-shot examples inside the user turn
- **Sampling parameters** — adjust `temperature`, `top_p`, or use majority voting across multiple samples
- **Fine-tuning** — the competition allows model fine-tuning; see the course resources for guidance

Good luck!

## LoRA Training

In [13]:
!.venv/bin/python -m pip install peft trl pandas datasets

Requirement already satisfied: peft in ./.venv/lib/python3.13/site-packages (0.19.1)
Requirement already satisfied: trl in ./.venv/lib/python3.13/site-packages (1.5.1)
Requirement already satisfied: pandas in ./.venv/lib/python3.13/site-packages (3.0.3)
Requirement already satisfied: datasets in ./.venv/lib/python3.13/site-packages (4.8.5)
Requirement already satisfied: numpy>=1.17 in ./.venv/lib/python3.13/site-packages (from peft) (2.4.6)
Requirement already satisfied: packaging>=20.0 in ./.venv/lib/python3.13/site-packages (from peft) (26.2)
Requirement already satisfied: psutil in ./.venv/lib/python3.13/site-packages (from peft) (7.2.2)
Requirement already satisfied: pyyaml in ./.venv/lib/python3.13/site-packages (from peft) (6.0.3)
Requirement already satisfied: torch>=1.13.0 in ./.venv/lib/python3.13/site-packages (from peft) (2.11.0)
Requirement already satisfied: transformers in ./.venv/lib/python3.13/site-packages (from peft) (5.9.0)
Requirement already satisfied: tqdm in ./.venv/lib/python3.13/site-packages (from peft) (4.67.3)
Requirement already satisfied: accelerate>=0.21.0 in ./.venv/lib/python3.13/site-packages (from peft) (1.13.0)
Requirement already satisfied: safetensors in ./.venv/lib/python3.13/site-packages (from peft) (0.7.0)
Requirement already satisfied: huggingface_hub>=0.25.0 in ./.venv/lib/python3.13/site-packages (from peft) (1.17.0)
Requirement already satisfied: jinja2 in ./.venv/lib/python3.13/site-packages (from trl) (3.1.6)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: filelock in ./.venv/lib/python3.13/site-packages (from datasets) (3.29.0)
Requirement already satisfied: pyarrow>=21.0.0 in ./.venv/lib/python3.13/site-packages (from datasets) (24.0.0)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in ./.venv/lib/python3.13/site-packages (from datasets) (0.4.1)
Requirement already satisfied: requests>=2.32.2 in ./.venv/lib/python3.13/site-packages (from datasets) (2.34.2)
Requirement already satisfied: httpx<1.0.0 in ./.venv/lib/python3.13/site-packages (from datasets) (0.28.1)
Requirement already satisfied: xxhash in ./.venv/lib/python3.13/site-packages (from datasets) (3.7.0)
Requirement already satisfied: multiprocess<0.70.20 in ./.venv/lib/python3.13/site-packages (from datasets) (0.70.19)
Requirement already satisfied: fsspec<=2026.2.0,>=2023.1.0 in ./.venv/lib/python3.13/site-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2026.2.0)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in ./.venv/lib/python3.13/site-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (3.13.5)
Requirement already satisfied: anyio in ./.venv/lib/python3.13/site-packages (from httpx<1.0.0->datasets) (4.13.0)
Requirement already satisfied: certifi in ./.venv/lib/python3.13/site-packages (from httpx<1.0.0->datasets) (2026.5.20)
Requirement already satisfied: httpcore==1.* in ./.venv/lib/python3.13/site-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in ./.venv/lib/python3.13/site-packages (from httpx<1.0.0->datasets) (3.17)
Requirement already satisfied: h11>=0.16 in ./.venv/lib/python3.13/site-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: click>=8.4.0 in ./.venv/lib/python3.13/site-packages (from huggingface_hub>=0.25.0->peft) (8.4.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in ./.venv/lib/python3.13/site-packages (from huggingface_hub>=0.25.0->peft) (1.5.0)
Requirement already satisfied: typer<0.26.0,>=0.20.0 in ./.venv/lib/python3.13/site-packages (from huggingface_hub>=0.25.0->peft) (0.25.1)
Requirement already satisfied: typing-extensions>=4.1.0 in ./.venv/lib/python3.13/site-packages (from huggingface_hub>=0.25.0->peft) (4.15.0)
Requirement already satisfied: shellingham>=1.3.0 in ./.venv/lib/python3.13/site-packages (from typer<0.26.0,>=0.20.0->huggingface_hub>=0.25.0->peft) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in ./.venv/lib/python3.13/site-packages (from typer<0.26.0,>=0.20.0->huggingface_hub>=0.25.0->peft) (15.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in ./.venv/lib/python3.13/site-packages (from typer<0.26.0,>=0.20.0->huggingface_hub>=0.25.0->peft) (0.0.4)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in ./.venv/lib/python3.13/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2.6.2)
Requirement already satisfied: aiosignal>=1.4.0 in ./.venv/lib/python3.13/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in ./.venv/lib/python3.13/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in ./.venv/lib/python3.13/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in ./.venv/lib/python3.13/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in ./.venv/lib/python3.13/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in ./.venv/lib/python3.13/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.24.2)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in ./.venv/lib/python3.13/site-packages (from requests>=2.32.2->datasets) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.26 in ./.venv/lib/python3.13/site-packages (from requests>=2.32.2->datasets) (2.7.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in ./.venv/lib/python3.13/site-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface_hub>=0.25.0->peft) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in ./.venv/lib/python3.13/site-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface_hub>=0.25.0->peft) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in ./.venv/lib/python3.13/site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface_hub>=0.25.0->peft) (0.1.2)
Requirement already satisfied: setuptools<82 in ./.venv/lib/python3.13/site-packages (from torch>=1.13.0->peft) (80.10.2)
Requirement already satisfied: sympy>=1.13.3 in ./.venv/lib/python3.13/site-packages (from torch>=1.13.0->peft) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in ./.venv/lib/python3.13/site-packages (from torch>=1.13.0->peft) (3.6.1)
Requirement already satisfied: cuda-toolkit==13.0.2 in ./.venv/lib/python3.13/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.13.0->peft) (13.0.2)
Requirement already satisfied: cuda-bindings<14,>=13.0.3 in ./.venv/lib/python3.13/site-packages (from torch>=1.13.0->peft) (13.3.1)
Requirement already satisfied: nvidia-cudnn-cu13==9.19.0.56 in ./.venv/lib/python3.13/site-packages (from torch>=1.13.0->peft) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu13==0.8.0 in ./.venv/lib/python3.13/site-packages (from torch>=1.13.0->peft) (0.8.0)
Requirement already satisfied: nvidia-nccl-cu13==2.28.9 in ./.venv/lib/python3.13/site-packages (from torch>=1.13.0->peft) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu13==3.4.5 in ./.venv/lib/python3.13/site-packages (from torch>=1.13.0->peft) (3.4.5)
Requirement already satisfied: triton==3.6.0 in ./.venv/lib/python3.13/site-packages (from torch>=1.13.0->peft) (3.6.0)
Requirement already satisfied: nvidia-cublas==13.1.0.3.* in ./.venv/lib/python3.13/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.13.0->peft) (13.1.0.3)
Requirement already satisfied: nvidia-cuda-runtime==13.0.96.* in ./.venv/lib/python3.13/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.13.0->peft) (13.0.96)
Requirement already satisfied: nvidia-cufft==12.0.0.61.* in ./.venv/lib/python3.13/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.13.0->peft) (12.0.0.61)
Requirement already satisfied: nvidia-cufile==1.15.1.6.* in ./.venv/lib/python3.13/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.13.0->peft) (1.15.1.6)
Requirement already satisfied: nvidia-cuda-cupti==13.0.85.* in ./.venv/lib/python3.13/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.13.0->peft) (13.0.85)
Requirement already satisfied: nvidia-curand==10.4.0.35.* in ./.venv/lib/python3.13/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.13.0->peft) (10.4.0.35)
Requirement already satisfied: nvidia-cusolver==12.0.4.66.* in ./.venv/lib/python3.13/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.13.0->peft) (12.0.4.66)
Requirement already satisfied: nvidia-cusparse==12.6.3.3.* in ./.venv/lib/python3.13/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.13.0->peft) (12.6.3.3)
Requirement already satisfied: nvidia-nvjitlink==13.0.88.* in ./.venv/lib/python3.13/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.13.0->peft) (13.0.88)
Requirement already satisfied: nvidia-cuda-nvrtc==13.0.88.* in ./.venv/lib/python3.13/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.13.0->peft) (13.0.88)
Requirement already satisfied: nvidia-nvtx==13.0.85.* in ./.venv/lib/python3.13/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=1.13.0->peft) (13.0.85)
Requirement already satisfied: cuda-pathfinder>=1.4.2 in ./.venv/lib/python3.13/site-packages (from cuda-bindings<14,>=13.0.3->torch>=1.13.0->peft) (1.5.5)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in ./.venv/lib/python3.13/site-packages (from sympy>=1.13.3->torch>=1.13.0->peft) (1.3.0)
Requirement already satisfied: regex>=2025.10.22 in ./.venv/lib/python3.13/site-packages (from transformers->peft) (2026.5.9)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in ./.venv/lib/python3.13/site-packages (from transformers->peft) (0.22.2)
Requirement already satisfied: MarkupSafe>=2.0 in ./.venv/lib/python3.13/site-packages (from jinja2->trl) (3.0.3)

In [9]:
from peft import prepare_model_for_kbit_training, get_peft_model, LoraConfig, TaskType
from transformers import AutoModelForCausalLM, BitsAndBytesConfig
import pandas as pd
from datasets import Dataset, load_dataset, concatenate_datasets
from huggingface_hub import hf_hub_download
from trl import SFTTrainer, SFTConfig
import re

In [19]:
# Do not change

#removing bnb config for unquantized

#bnb_config = BitsAndBytesConfig(
#    load_in_4bit=True,
#    bnb_4bit_compute_dtype=torch.bfloat16,
#    bnb_4bit_quant_type="nf4",        # ← was missing, saves ~0.3GB
#    bnb_4bit_use_double_quant=True,
#)
model = AutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    trust_remote_code=True,
    #quantization_config=bnb_config, #uncomment for quant
    dtype=torch.bfloat16, #uncomment for unquant
    device_map="auto",
)

model.gradient_checkpointing_enable()
model = prepare_model_for_kbit_training(model)

# Can change r and lora_alpha as needed, r is rank and lora_alpha is a scaling factor. 
# Higher values of lora_alpha can lead to better performance but require more training time and resources.
# Usually lora_alpha = r * 2, although not required.
# Common: r=64, lora_alpha=128
lora_config = LoraConfig(
    r=64,
    lora_alpha=128,
    target_modules=["qkv_proj", "o_proj", "gate_up_proj", "down_proj"],
    lora_dropout=0.05,
    bias="none",
    task_type=TaskType.CAUSAL_LM,
)
model = get_peft_model(model, lora_config)

model.print_trainable_parameters()

Loading weights:   0%|          | 0/398 [00:00<?, ?it/s]

trainable params: 43,646,976 || all params: 4,066,115,072 || trainable%: 1.0734

In [10]:
from peft import PeftModel

model = AutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    trust_remote_code=True,
    dtype=torch.bfloat16,
    device_map="auto",
)
model.gradient_checkpointing_enable()
model = PeftModel.from_pretrained(
    model,
    "./lora_adapters/lora_adapter_openr1_s1k/lora_adapter_openr1_s1k",
    is_trainable=True,
)
model.print_trainable_parameters()

Loading weights:   0%|          | 0/398 [00:00<?, ?it/s]

trainable params: 21,823,488 || all params: 4,044,291,584 || trainable%: 0.5396

### qwedsacf/competition_math Dataset
Not very good, only free response questions

In [ ]:
tokenizer = AutoTokenizer.from_pretrained(MODEL_ID, use_fast=True)
tokenizer.pad_token = tokenizer.eos_token

# Load the Parquet file directly into Pandas
file_path = hf_hub_download(
    repo_id="qwedsacf/competition_math", 
    filename="data/train-00000-of-00001-7320a6f3aba8ebd2.parquet",
    repo_type="dataset",
)
ds = pd.read_parquet(file_path)
ds = ds[ds["solution"].str.contains(r"\\boxed\{(.+?)\}", na=False)] # Ignore the warning
ds = ds.reset_index(drop=True)

# Add the lora training prompt formatting
def lora_thinking_prompt(example):
    system = "You are a helpful assistant that thinks step-by-step."
    user = example["problem"]
    solution = example["solution"]
    answer = re.search(r"\\boxed\{(.+?)\}", solution).group()
    
    assistant_content = f"<think>\n{solution}\n</think>\nFinal Answer: {answer}"
    
    messages = [
        {"role": "system", "content": system},
        {"role": "user", "content": user},
        {"role": "assistant", "content": assistant_content}
    ]
    return tokenizer.apply_chat_template(messages, tokenize=False)

# Process and convert to HF Dataset for training
ds["text"] = ds.apply(lora_thinking_prompt, axis=1)

lora_train_dataset = Dataset.from_pandas(ds[["text"]])

/tmp/ipykernel_19909/3832746221.py:11: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  ds = ds[ds["solution"].str.contains(r"\\boxed\{(.+?)\}", na=False)] # Ignore the warning

### open-r1/OpenR1-Math-220k Dataset
Has both free response and multiple choice

In [11]:
# Number of cores for parallel processing - adjust based on your machine
CORES = 4

tokenizer = AutoTokenizer.from_pretrained(MODEL_ID, use_fast=True)
tokenizer.pad_token = tokenizer.eos_token

# Helper function to filter out samples without valid reasoning and correct math verification
def has_valid_reasoning(example):
    for comp, ver in zip(example["is_reasoning_complete"], example["correctness_math_verify"]):
        if comp == True and ver == True:
            return True
    return False

# Load the Dataset directly using Hugging Face Datasets library
ds = load_dataset("open-r1/OpenR1-Math-220k", "default") # Total dataset is 93.7k
# Pick first 3000 MCQ samples
mcq_ds = ds["train"].filter(
    lambda x: x["question_type"] == "MCQ" and has_valid_reasoning(x) and x["answer"].isalpha(), 
    num_proc=CORES
).select(range(3000)) 
# Pick first 7000 word problem samples
word_prob_ds = ds["train"].filter(
    lambda x: x["question_type"] == "math-word-problem" and has_valid_reasoning(x), 
    num_proc=CORES
).select(range(7000)) 
ds = concatenate_datasets([mcq_ds, word_prob_ds]) # Combine for 10k total samples

# Add the lora training prompt formatting
def lora_thinking_prompt_map(example):
    question_type = example["question_type"]
    system = SYSTEM_PROMPT_MCQ if question_type == "MCQ" else SYSTEM_PROMPT_MATH

    user = example["problem"]

    generations = example["generations"]
    is_reasoning_complete = example["is_reasoning_complete"]
    correctness_math_verify = example["correctness_math_verify"]
    solution = None
    for gen, comp, ver in zip(generations, is_reasoning_complete, correctness_math_verify):
        if comp == True and ver == True:
            solution = gen
            break
    if solution is None:
        return {"text": None}

    answer = f"\\boxed{{{example['answer']}}}"

    assistant_content = f"<think>\n{solution}\n</think>\nFinal Answer: {answer}"
    
    messages = [
        {"role": "system", "content": system},
        {"role": "user", "content": user},
        {"role": "assistant", "content": assistant_content}
    ]
    
    return {"text": tokenizer.apply_chat_template(messages, tokenize=False)}

# Process the dataset
lora_train_dataset = ds.map(
    lora_thinking_prompt_map,
    remove_columns=ds.column_names,
    num_proc=CORES
)

lora_train_dataset = lora_train_dataset.filter(
    lambda x: x["text"] is not None, 
    num_proc=CORES
)

#shuffling in questions from the public json dataset aswell. 
comp_records = []
for item in data:
    system = SYSTEM_PROMPT_MCQ if item.get("options") else SYSTEM_PROMPT_MATH
    answer = item["answer"]
    if isinstance(answer, list):
        answer = ", ".join(str(a) for a in answer)
    messages = [
        {"role": "system", "content": system},
        {"role": "user", "content": item["question"]},
        {"role": "assistant", "content": f"<think>\n</think>\nFinal Answer: \\boxed{{{answer}}}"}
    ]
    comp_records.append({"text": tokenizer.apply_chat_template(messages, tokenize=False)})

comp_ds = Dataset.from_list(comp_records)
lora_train_dataset = concatenate_datasets([lora_train_dataset, comp_ds]).shuffle(seed=42)

lora_train_dataset = lora_train_dataset.shuffle(seed=42)

Resolving data files:   0%|          | 0/20 [00:00<?, ?it/s]

In [12]:
print(len(lora_train_dataset))
print(lora_train_dataset[0])
#print(lora_train_dataset[1])
#print(lora_train_dataset[2])
#print(lora_train_dataset[3])
#print(lora_train_dataset[4])

11126
{'text': '<|im_start|>system\nYou are an expert mathematician. Think freely and explore multiple approaches before committing to one. If you realize you made an error, correct it immediately and try a different approach. Always use Chinese for your reasoning and thought process, but your final answer must be in English. Put your final answer inside \\boxed{}. If the problem has multiple sub-answers, separate them by commas inside a single \\boxed{}, e.g. \\boxed{3, 7}.<|im_end|>\n<|im_start|>user\nOn a clearing, ladybugs gathered. If a ladybug has six spots on its back, it always tells the truth, and if it has four spots, it always lies, and there were no other ladybugs on the clearing. The first ladybug said: "Each of us has the same number of spots on our backs." The second said: "All of us together have 30 spots on our backs." - "No, all of us together have 26 spots on our backs," - the third one objected. "Exactly one of these three told the truth," - each of the other ladybugs declared. How many ladybugs gathered on the clearing?<|im_end|>\n<|im_start|>assistant\n<think>\nOkay, let\'s try to solve this ladybug problem. Hmm, so we have ladybugs with either six spots (truth-tellers) or four spots (liars). There are three ladybugs that made statements, and then all the others each said that exactly one of the three told the truth. We need to find out how many ladybugs there are in total.\n\nFirst, let\'s summarize the given information:\n\n1. Ladybugs with 6 spots always tell the truth.\n2. Ladybugs with 4 spots always lie.\n3. There are three specific ladybugs:\n   - The first said: "Each of us has the same number of spots on our backs."\n   - The second said: "All of us together have 30 spots on our backs."\n   - The third said: "No, all of us together have 26 spots on our backs."\n4. Each of the other ladybugs (so, the ones beyond the first three) declared: "Exactly one of these three told the truth."\n\nThe problem states that exactly one of the three told the truth (as per the declarations of the other ladybugs). Wait, but each of the other ladybugs said that "Exactly one of these three told the truth." But since these other ladybugs could be either truth-tellers or liars, their statements need to be considered carefully. If a ladybug is telling the truth (6 spots), then their statement that "Exactly one of these three told the truth" must be true. If they are lying (4 spots), then their statement is false, meaning it\'s not true that exactly one of the three told the truth; so either zero, two, or all three of the first three ladybugs told the truth.\n\nBut the problem says: "Exactly one of these three told the truth," - each of the other ladybugs declared. Wait, so all the other ladybugs (so if there are N total ladybugs, the other N-3) each made that same statement. So all the others are saying "Exactly one of the first three told the truth." So if any of these other ladybugs is truthful (6 spots), then their statement is true, so exactly one of the first three is truthful. If any of these others is a liar (4 spots), then their statement is false, so it\'s not exactly one of the first three that told the truth; so the number of truthful among the first three would be 0, 2, or 3. However, the problem states "each of the other ladybugs declared" that exactly one of the three told the truth. So all of these other ladybugs made the same statement, but depending on whether they are truth-tellers or liars, their statement\'s validity changes.\n\nBut the problem says: "Exactly one of these three told the truth," - each of the other ladybugs declared. So, the key here is that all the other ladybugs (excluding the first three) have made the same statement. Therefore, either all of them are telling the truth (so exactly one of the first three is truthful), or all of them are lying (so the number of truthful among the first three is not one, i.e., 0, 2, or 3). But since the other ladybugs can be a mix of truth-tellers and liars, but they all made the same statement. Wait, but in the problem statement, it\'s not specified whether these other ladybugs are making individual statements or if they all made the same statement. The problem says: "\'Exactly one of these three told the truth,\' - each of the other ladybugs declared." So each of them individually declared that same statement. Therefore, each of these other ladybugs is asserting that exactly one of the first three told the truth. So depending on their type (truth-teller or liar), their statements must be evaluated.\n\nSo, suppose there are k ladybugs in total. The first three made their statements, and the remaining (k - 3) each said "Exactly one of these three told the truth." Let\'s denote the number of truth-tellers (6-spot ladybugs) as T and liars (4-spot ladybugs) as L. So total ladybugs k = T + L. Each of the other ladybugs (k - 3) made the statement about exactly one of the first three being truthful.\n\nLet me break down the possibilities:\n\nFirst, analyze the statements of the first three ladybugs.\n\n1. First ladybug: "Each of us has the same number of spots on our backs." If this is a truth-teller (6 spots), then all ladybugs (including herself) have 6 spots. But that would mean all are truth-tellers, so the second and third ladybugs would also be truth-tellers, but the second said total spots are 30, third said 26. If all are truth-tellers, then both second and third would be telling the truth, but they contradict each other. Therefore, the first ladybug cannot be a truth-teller. Therefore, the first ladybug must be a liar (4 spots). Therefore, the statement "Each of us has the same number of spots on our backs" is false. So, not all ladybugs have the same number of spots. So there are both 4-spot and 6-spot ladybugs.\n\n2. Second ladybug: "All of us together have 30 spots on our backs." Let\'s denote total spots as S. If this ladybug is a truth-teller (6 spots), then S = 30. If she is a liar (4 spots), then S ≠ 30.\n\n3. Third ladybug: "All of us together have 26 spots on our backs." Similarly, if this ladybug is a truth-teller, S = 26; if a liar, S ≠ 26.\n\nNow, each of the other ladybugs (the ones beyond the first three) said that "Exactly one of these three told the truth." So, for each of these other ladybugs, if they are truth-tellers (6 spots), then exactly one of the first three is truthful. If they are liars (4 spots), then it\'s not the case that exactly one of the first three is truthful, i.e., 0, 2, or 3 of the first three are truthful.\n\nBut here\'s the key: Since all of these other ladybugs made the same statement, we have to consider the possibility that they are either all telling the truth or all lying, or a mix. Wait, but they can be a mix. However, if some are telling the truth and others lying, then that complicates things. But the problem states that "each of the other ladybugs declared," so each of them individually made that statement. Therefore, their individual truthfulness depends on their type.\n\nBut since the problem says "exactly one of these three told the truth," each of the other ladybugs declared. So the conclusion is that the statement "exactly one of the three told the truth" must be true if declared by a truth-teller, and false if declared by a liar.\n\nBut to solve this, perhaps we need to consider that the actual number of truthful statements among the first three must be such that when considering the other ladybugs\' declarations, the total number of spots adds up correctly.\n\nLet me try to approach this step by step.\n\nFirst, from the first ladybug\'s statement: she is a liar, as we concluded, because if she were truthful, all would have the same number of spots, leading to a contradiction. So first ladybug has 4 spots.\n\nTherefore, among the first three, the first is a liar (4 spots). The second and third could be either truth-tellers or liars. Let\'s consider possible scenarios for the number of truth-tellers among the first three.\n\nCase 1: Exactly one of the first three is truthful (i.e., either the second or the third). Then the other ladybugs (the ones beyond the first three) would be making a true statement if they are truth-tellers, or a false statement if they are liars. But since all of the other ladybugs are saying "exactly one of these three told the truth," if exactly one is truthful, then the truth-tellers among the other ladybugs are telling the truth, and the liars among them are lying. But how does this affect the total number of spots?\n\nCase 2: Zero of the first three are truthful. Then the other ladybugs\' statement "exactly one..." would be false, so if an other ladybug is a liar, their statement is false, which would be consistent. If an other ladybug is a truth-teller, their statement would be false, which is impossible. Therefore, in this case, all other ladybugs must be liars. Because if there were any truth-tellers among them, their statement would have to be true, which would contradict the fact that zero of the first three are truthful.\n\nCase 3: Two of the first three are truthful. Then the other ladybugs\' statement "exactly one..." is false, so any liar among the other ladybugs would be telling the truth (since their statement is false), but wait, no. Wait, if the other ladybugs are liars, then their statement "exactly one..." is a lie, so the reality would be that it\'s not exactly one, i.e., 0, 2, or 3. So if two of the first three are truthful, then the other ladybugs, if they are liars, are correctly lying. If they are truth-tellers, they would be incorrectly stating "exactly one," which would be false. Therefore, in this case, the other ladybugs must all be liars.\n\nCase 4: All three of the first three are truthful. But we already know the first one is a liar, so this case is impossible.\n\nSo possible cases for the number of truthful among the first three: 0, 1, or 2. But since the first is a liar, possible numbers are 0 (second and third are liars), 1 (either second or third is truthful), or 2 (both second and third are truthful). Wait, but earlier, we saw that if the first is a liar, so the rest can vary. Wait, actually, if first is a liar, the second and third can be either truth-tellers or liars. So possible truthful counts among first three: 0, 1, or 2.\n\nBut let\'s analyze each case:\n\nCase 1: Exactly one of the first three is truthful. Then, the other ladybugs (k - 3) must consist of some truth-tellers and liars. The truth-tellers among them would correctly state that exactly one is truthful, and the liars among them would falsely state that exactly one is truthful (when in reality it\'s true, so their lie would be... Wait, if exactly one is truthful, then the statement "exactly one..." is true. Therefore, if a liar among the other ladybugs says "exactly one...," which is actually true, then the liar is telling the truth, which contradicts them being liars. Therefore, in this case, if exactly one of the first three is truthful, then all the other ladybugs must be truth-tellers, because if any of them were liars, they would be forced to tell the truth, which they cannot do. Therefore, if Case 1 holds (exactly one truthful among first three), then all other ladybugs must be truth-tellers. Therefore, the other ladybugs (k - 3) are all 6-spot ladybugs. So total spots would be:\n\nFirst three: first is liar (4), second and third: one is truthful (6) and one is liar (4), since exactly one truthful. Then the other (k - 3) are all truthful (6 each). So total spots S = 4 + (6 + 4) + 6*(k - 3). Wait, but if exactly one of the first three is truthful, then in the first three, one is truthful (6) and two are liars (4 each). So total spots for first three: 4 + 4 + 6 = 14. Then the other (k - 3) ladybugs are all truth-tellers, each with 6 spots: 6*(k - 3). So total spots S = 14 + 6*(k - 3) = 14 + 6k - 18 = 6k - 4.\n\nBut also, depending on which of the second or third is truthful, the total spots S would be either 30 or 26. If the second ladybug is truthful, then S = 30. If the third is truthful, S = 26. But according to the total spots formula from Case 1: S = 6k - 4. So:\n\nIf the second is truthful (S = 30):\n\n6k - 4 = 30 → 6k = 34 → k = 34/6 ≈ 5.666, which is not an integer. Disregard.\n\nIf the third is truthful (S = 26):\n\n6k - 4 = 26 → 6k = 30 → k = 5. So total ladybugs would be 5. Let\'s check:\n\nFirst three: 4 (liar) + 4 (liar) + 6 (truthful third) = 14. Then other ladybugs: 5 - 3 = 2, each with 6 spots: 12. Total spots: 14 + 12 = 26, which matches the third ladybug\'s statement. So this seems possible. However, in this case, the other ladybugs (2 of them) are all truth-tellers. Therefore, they each have 6 spots, and they told the truth that exactly one of the first three is truthful. That works.\n\nBut wait, let\'s check the total number of spots: 26. So third ladybug is truthful, second is liar. First is liar, as established. Then total spots: 4 (first) + 4 (second) + 6 (third) + 6*2 (others) = 4 + 4 + 6 + 12 = 26. Correct. So total ladybugs: 5. But let\'s see if this conflicts with anything else.\n\nWait, but in this case, the second ladybug lied about the total spots being 30, which is consistent because the actual total is 26. The first ladybug lied about all having the same number of spots. The third told the truth. The other two ladybugs (fourth and fifth) are truth-tellers, each with 6 spots, and they correctly stated that exactly one of the first three told the truth. So this seems consistent. So k=5 is a possible answer.\n\nBut we need to check other cases to make sure.\n\nCase 2: Zero of the first three are truthful. So all three are liars. Then, the other ladybugs (k - 3) each said "exactly one of these three told the truth." Since in reality, zero of the first three told the truth, then the statement "exactly one..." is false. Therefore, if an other ladybug is a truth-teller, they would be lying, which is impossible. Therefore, all other ladybugs must be liars. Therefore, all other ladybugs (k - 3) are liars with 4 spots each.\n\nTotal spots would be: first three: 4 each, so 12. Other ladybugs: 4*(k - 3). So total S = 12 + 4*(k - 3) = 12 + 4k - 12 = 4k.\n\nBut since the second and third ladybugs are liars, their statements (30 and 26) are both false. Therefore, total spots cannot be 30 or 26. So S = 4k ≠ 30 and 4k ≠26. Therefore, 4k must be some other number.\n\nBut we need to check if this is possible. Let\'s see:\n\nTotal spots S = 4k. Also, in this case, the other ladybugs are all liars, so they have 4 spots each. Therefore, the number of ladybugs is k, with the first three being liars (4 spots each) and the rest k - 3 also liars (4 spots each). Therefore, all ladybugs are liars with 4 spots. Therefore, S = 4k. But the first ladybug said "Each of us has the same number of spots on our backs." If all are liars, then they all have 4 spots, so the statement "Each of us has the same number of spots" would be true. But the first ladybug is a liar, so she cannot tell the truth. Therefore, this is a contradiction. Therefore, Case 2 is impossible. Because if all ladybugs were liars (4 spots), then the first ladybug\'s statement would be true, but she is supposed to be a liar. Hence, contradiction. Therefore, Case 2 is invalid.\n\nCase 3: Two of the first three are truthful. But wait, the first ladybug is a liar, so only the second and third could be truthful. So if two of the first three are truthful, that would mean the second and third are both truthful. But they made conflicting statements: second said total spots are 30, third said 26. If both are truthful, then total spots would have to be both 30 and 26, which is impossible. Therefore, Case 3 is invalid. So the only possible case is Case 1, where exactly one of the first three is truthful, leading to k=5.\n\nWait, but let\'s verify again. If k=5, total spots 26. Let\'s check the types:\n\nLadybugs 1: 4 spots (liar)\nLadybug 2: 4 spots (liar)\nLadybug 3: 6 spots (truth-teller)\nLadybugs 4 and 5: 6 spots each (truth-tellers)\n\nEach of the other ladybugs (4 and 5) declared that exactly one of the first three told the truth. Since ladybugs 4 and 5 are truth-tellers, their statement is true: exactly one (ladybug 3) told the truth. That works.\n\nTotal spots: 4 + 4 + 6 + 6 + 6 = 26, which matches ladybug 3\'s statement. Ladybug 2\'s statement was 30, which is false, as expected since she\'s a liar. Ladybug 1\'s statement that all have the same number of spots is false, which is correct. So this seems consistent.\n\nBut wait, are there any other possibilities in Case 1? For example, if instead of the third ladybug being truthful, the second one is. Let\'s see:\n\nIf the second ladybug is truthful (total spots 30), and the first and third are liars. Then total spots S = 30. From Case 1, total spots S = 6k - 4. So 6k - 4 = 30 → 6k = 34 → k = 34/6 ≈ 5.666, which isn\'t an integer. Therefore, impossible. Hence, only if the third ladybug is truthful do we get an integer number of ladybugs (k=5). Therefore, the only valid solution is k=5.\n\nBut let\'s check if there are any other cases we might have missed. We considered 0, 1, or 2 truthful among the first three. But since the first is a liar, 2 truthful would mean second and third are truthful, which is impossible due to conflicting statements. 0 truthful leads to contradiction. Therefore, only Case 1 is possible, leading to k=5.\n\nHence, the number of ladybugs is 5.\n\n**Final Answer**\n\\boxed{5}\n</think>\n\nFinal Answer: \\boxed{5}<|im_end|>\n'}

In [ ]:
# CHECKPOINT_DIR = "./lora_adapters/lora_adapter_comp/checkpoints"
# MODEL_DIR = "./lora_adapters/lora_adapter_comp/lora_adapter_comp"

CHECKPOINT_DIR = "./lora_adapters/unquant_lora_adapter_openr1_generate/checkpoints"
MODEL_DIR = "./lora_adapters/lora_adapter_openr1_generate/lora_adapter_openr1_generate"

# Can change these parameters as needed
sft_config = SFTConfig(
    output_dir=CHECKPOINT_DIR,
    max_length=4096, # Samples can be up to 3k tokens, use at leask 4k to avoid truncation.
    dataset_text_field="text",
    packing=False,
    per_device_train_batch_size=1,
    gradient_accumulation_steps=50,
    learning_rate=1e-4,
    lr_scheduler_type="cosine",
    warmup_ratio=0.1,
    bf16=True,
    optim="adamw_8bit",
    num_train_epochs=1,
    save_strategy="steps",
    save_steps=10,
)

# Do not change
trainer = SFTTrainer(
    model = model,
    train_dataset = lora_train_dataset,
    args=sft_config,
)

trainer.train()

trainer.save_model(MODEL_DIR)
tokenizer.save_pretrained(MODEL_DIR)

In [13]:
import gc
from transformers import TrainerCallback
from trl import GRPOTrainer, GRPOConfig
import re

# ── Cache-clearing callback ───────────────────────────────────────────────────
class ClearCacheCallback(TrainerCallback):
    def on_step_begin(self, args, state, control, **kwargs):
        gc.collect()
        torch.cuda.empty_cache()
        torch.cuda.reset_peak_memory_stats()   # ← resets the high-water mark

    def on_step_end(self, args, state, control, **kwargs):
        gc.collect()
        torch.cuda.empty_cache()

# ── Dataset ───────────────────────────────────────────────────────────────────
MAX_PROMPT_TOKENS = 512   # restore some prompt context

def make_grpo_dataset(hf_dataset):
    records = []
    for example in hf_dataset:
        question_type = "options" in example.keys()
        system = SYSTEM_PROMPT_MCQ_SHORT if question_type else SYSTEM_PROMPT_MATH_SHORT

        prompt_text = tokenizer.apply_chat_template(
            [
                {"role": "system", "content": system},
                {"role": "user",   "content": example["question"]},
            ],
            tokenize=False,
            add_generation_prompt=True,
        )
        # Force the model's first tokens to be \boxed{ so it MUST complete the answer
        prompt_text += "\\boxed{"

        token_ids = tokenizer(
            prompt_text,
            truncation=True,
            max_length=256,
            add_special_tokens=False,
        ).input_ids
        prompt_text = tokenizer.decode(token_ids, skip_special_tokens=False)

        answer = example["answer"]
        if isinstance(answer, list):
            answer = ", ".join(str(a) for a in answer)
        else:
            answer = str(answer)

        records.append({
            "prompt": prompt_text,
            "answer": answer,
            "question_type": question_type,
        })
    from datasets import Dataset
    return Dataset.from_list(records)

grpo_dataset = make_grpo_dataset(data)
grpo_dataset = grpo_dataset.shuffle(seed=42)
print(f"GRPO dataset size: {len(grpo_dataset)}")

# ── Reward function ───────────────────────────────────────────────────────────
def extract_boxed(text: str) -> str:
    # The completion starts mid-boxed: model outputs "A}" or "42}"
    # so first try to grab everything before the first closing brace
    text = text.strip()
    
    # Try normal extraction first (in case model outputs another \boxed{})
    matches = []
    for m in re.finditer(r"\\boxed\{", text):
        start = m.end()
        depth, i = 1, start
        while i < len(text) and depth > 0:
            if text[i] == "{": depth += 1
            elif text[i] == "}": depth -= 1
            i += 1
        if depth == 0:
            matches.append(text[start : i - 1].strip())
    if matches:
        return matches[-1]
    
    # Fallback: prompt ended with \boxed{, so completion is "answer}"
    brace_end = text.find("}")
    if brace_end != -1:
        return text[:brace_end].strip()
    
    return text.strip()  # last resort: use whatever was generated


#changed reqard function to reward partial credit, as loss is 0 for too long
def math_accuracy_reward(completions, answer, question_type, **kwargs):
    rewards = []
    for completion, gold, qtype in zip(completions, answer, question_type):
        pred = extract_boxed(completion)
        print(f"PRED: {repr(pred[:50])} | GOLD: {repr(gold[:50])}")  # ← add here
        if qtype:
            correct = pred.upper() == gold.strip().upper()
            rewards.append(1.0 if correct else 0.0)
        else:
            # Split multi-part answers and score each part
            gold_parts = [g.strip() for g in gold.split(",")]
            if len(gold_parts) == 1:
                # Single answer, use judger as before
                try:
                    correct = judger.auto_judge(
                        pred=pred,
                        gold=gold_parts,
                        options=[[]] * len(gold_parts),
                    )
                    rewards.append(1.0 if correct else 0.0)
                except Exception:
                    rewards.append(0.0)
            else:
                # Multi-part: give partial credit per correct part
                correct_parts = 0
                for part in gold_parts:
                    try:
                        if judger.auto_judge(
                            pred=pred,
                            gold=[part],
                            options=[[]],
                        ):
                            correct_parts += 1
                    except Exception:
                        pass
                rewards.append(correct_parts / len(gold_parts))

    print(f"rewards: {rewards} | golds: {list(answer)}")
    return rewards

# ── Config ────────────────────────────────────────────────────────────────────
# grpo_config = GRPOConfig(
#     output_dir="./lora_adapters/lora_grpo/checkpoints",
#     num_generations=4,
#     max_completion_length=256,

#     per_device_train_batch_size=1,
#     gradient_accumulation_steps=32,
#     learning_rate=5e-6,
#     num_train_epochs=2,
#     warmup_ratio=0.05,
#     bf16=True,
#     optim="adamw_8bit",
#     dataloader_pin_memory=False,
#     dataloader_num_workers=0,

#     logging_steps=5,
#     save_strategy="steps",
#     save_steps=10,
#     logging_dir="./logs/grpo",

#     beta=0.0,      # ← eliminates the reference model copy, saves ~2.5GB
#     epsilon=0.1,

    

# )

# grpo_config.save_safetensors = False

# # ── Train ─────────────────────────────────────────────────────────────────────
# gc.collect()
# torch.cuda.empty_cache()
# print(f"Free GPU memory before init: {torch.cuda.mem_get_info()[0]/1024**3:.2f} GB")

# grpo_trainer = GRPOTrainer(
#     model=model,
#     args=grpo_config,
#     train_dataset=grpo_dataset,
#     reward_funcs=math_accuracy_reward,
#     callbacks=[ClearCacheCallback()],   # ← clears cache every step
# )

# #grpo_trainer.train(resume_from_checkpoint="./lora_adapters/lora_grpo/checkpoints/checkpoint-1250")
# grpo_trainer.train()

# grpo_trainer.save_model("./lora_adapters/lora_grpo/lora_grpov3")
# tokenizer.save_pretrained("./lora_adapters/lora_grpo/lora_grpov3")


#NEW TRAINING 

class SaveCallback(TrainerCallback):
    def on_step_end(self, args, state, control, **kwargs):
        if state.global_step % 50 == 0 and state.global_step > 0:
            model.save_pretrained(f"./lora_adapters/lora_grpo/checkpoints/step-{state.global_step}")
            tokenizer.save_pretrained(f"./lora_adapters/lora_grpo/checkpoints/step-{state.global_step}")

grpo_config = GRPOConfig(
    output_dir="./lora_adapters/lora_grpo/checkpoints",
    num_generations=4,
    max_completion_length=256,
    per_device_train_batch_size=1,
    gradient_accumulation_steps=32,
    learning_rate=5e-6,
    num_train_epochs=1,
    warmup_ratio=0.05,
    bf16=True,
    optim="adamw_8bit",
    dataloader_pin_memory=False,
    dataloader_num_workers=0,
    logging_steps=5,
    save_strategy="no",
    logging_dir="./logs/grpo",
    beta=0.0,
    epsilon=0.1,
)

gc.collect()
torch.cuda.empty_cache()

grpo_trainer = GRPOTrainer(
    model=model,
    args=grpo_config,
    train_dataset=grpo_dataset,
    reward_funcs=math_accuracy_reward,
    callbacks=[ClearCacheCallback(), SaveCallback()],
)

grpo_trainer.train()

model.save_pretrained("./lora_adapters/lora_grpo/lora_grpov3")
tokenizer.save_pretrained("./lora_adapters/lora_grpo/lora_grpov3")

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
[transformers] `logging_dir` is deprecated and will be removed in v5.2. Please set `TENSORBOARD_LOGGING_DIR` instead.

GRPO dataset size: 1126

[transformers] The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None, 'pad_token_id': 151643}.

PRED: 'inches' | GOLD: 'millimeters, meters, kilometers, meters, kilometer'
PRED: 'metric' | GOLD: 'millimeters, meters, kilometers, meters, kilometer'
PRED: 'cm' | GOLD: 'millimeters, meters, kilometers, meters, kilometer'
PRED: '1 \\text{ millimeter' | GOLD: 'millimeters, meters, kilometers, meters, kilometer'
PRED: 'D' | GOLD: 'G'
PRED: 'D' | GOLD: 'G'
PRED: 'D' | GOLD: 'G'
PRED: 'A' | GOLD: 'G'
PRED: '0.45, 1.12' | GOLD: '(0.72, -0.45)'
PRED: '0.57, 1.12, 1.35, 2.04' | GOLD: '(0.72, -0.45)'
PRED: '2.14, 1.23, 1.13, -0.53' | GOLD: '(0.72, -0.45)'
PRED: '1.01, -0.33, 0.52' | GOLD: '(0.72, -0.45)'
PRED: '664' | GOLD: '918'
PRED: '1112' | GOLD: '918'
PRED: '1054' | GOLD: '918'
PRED: '1020' | GOLD: '918'
PRED: '' | GOLD: '54, 46, 48, 1.24743, 2, 9.21034, B'
PRED: 'Let $e_{ij' | GOLD: '54, 46, 48, 1.24743, 2, 9.21034, B'
PRED: '(b) Find the expected number of people with medica' | GOLD: '54, 46, 48, 1.24743, 2, 9.21034, B'
PRED: '' | GOLD: '54, 46, 48, 1.24743, 2, 9.21034, B'
PRED: 'A' | GOLD: 'C'
PRED: 'A' | GOLD: 'C'
PRED: 'C' | GOLD: 'C'
PRED: 'D' | GOLD: 'C'
PRED: '170' | GOLD: 'a*5, a*10, a*25, a*10+25, 17*10'
PRED: '170' | GOLD: 'a*5, a*10, a*25, a*10+25, 17*10'
PRED: '5a' | GOLD: 'a*5, a*10, a*25, a*10+25, 17*10'
PRED: '170' | GOLD: 'a*5, a*10, a*25, a*10+25, 17*10'
PRED: '425' | GOLD: '68, 340'
PRED: '6499' | GOLD: '68, 340'
PRED: '272' | GOLD: '68, 340'
PRED: '329' | GOLD: '68, 340'
rewards: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0] | golds: ['millimeters, meters, kilometers, meters, kilometers, centimeters', 'millimeters, meters, kilometers, meters, kilometers, centimeters', 'millimeters, meters, kilometers, meters, kilometers, centimeters', 'millimeters, meters, kilometers, meters, kilometers, centimeters', 'G', 'G', 'G', 'G', '(0.72, -0.45)', '(0.72, -0.45)', '(0.72, -0.45)', '(0.72, -0.45)', '918', '918', '918', '918', '54, 46, 48, 1.24743, 2, 9.21034, B', '54, 46, 48, 1.24743, 2, 9.21034, B', '54, 46, 48, 1.24743, 2, 9.21034, B', '54, 46, 48, 1.24743, 2, 9.21034, B', 'C', 'C', 'C', 'C', 'a*5, a*10, a*25, a*10+25, 17*10', 'a*5, a*10, a*25, a*10+25, 17*10', 'a*5, a*10, a*25, a*10+25, 17*10', 'a*5, a*10, a*25, a*10+25, 17*10', '68, 340', '68, 340', '68, 340', '68, 340']

PRED: 'C' | GOLD: 'C'
PRED: 'C' | GOLD: 'C'
PRED: 'C' | GOLD: 'C'
PRED: 'C' | GOLD: 'C'
PRED: 'A' | GOLD: 'D'
PRED: 'D' | GOLD: 'D'
PRED: 'B' | GOLD: 'D'
PRED: 'D' | GOLD: 'D'
PRED: '-64' | GOLD: '25, 64, 9, -64'
PRED: '-64' | GOLD: '25, 64, 9, -64'
PRED: '-64' | GOLD: '25, 64, 9, -64'
PRED: '-64' | GOLD: '25, 64, 9, -64'
PRED: '1' | GOLD: '13, 49, 1E+06, 1'
PRED: '1' | GOLD: '13, 49, 1E+06, 1'
PRED: '1' | GOLD: '13, 49, 1E+06, 1'
PRED: '1' | GOLD: '13, 49, 1E+06, 1'
PRED: 'A' | GOLD: 'C'
PRED: 'C' | GOLD: 'C'
PRED: 'A' | GOLD: 'C'
PRED: 'E' | GOLD: 'C'
PRED: 'D' | GOLD: 'F'
PRED: 'C' | GOLD: 'F'
PRED: 'B' | GOLD: 'F'
PRED: 'D' | GOLD: 'F'
PRED: '320' | GOLD: '32'
PRED: '320' | GOLD: '32'
PRED: '320' | GOLD: '32'
PRED: '320' | GOLD: '32'
PRED: '10.70' | GOLD: '166.668, 3709.33, 3876*0.957^(t/10), 0.438554'
PRED: '\\%) (e) In which year will the forest cover drop b' | GOLD: '166.668, 3709.33, 3876*0.957^(t/10), 0.438554'
PRED: '%).' | GOLD: '166.668, 3709.33, 3876*0.957^(t/10), 0.438554'
PRED: 'decimal place.) \n(e) Using the formula from (c), c' | GOLD: '166.668, 3709.33, 3876*0.957^(t/10), 0.438554'
rewards: [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0] | golds: ['C', 'C', 'C', 'C', 'D', 'D', 'D', 'D', '25, 64, 9, -64', '25, 64, 9, -64', '25, 64, 9, -64', '25, 64, 9, -64', '13, 49, 1E+06, 1', '13, 49, 1E+06, 1', '13, 49, 1E+06, 1', '13, 49, 1E+06, 1', 'C', 'C', 'C', 'C', 'F', 'F', 'F', 'F', '32', '32', '32', '32', '166.668, 3709.33, 3876*0.957^(t/10), 0.438554', '166.668, 3709.33, 3876*0.957^(t/10), 0.438554', '166.668, 3709.33, 3876*0.957^(t/10), 0.438554', '166.668, 3709.33, 3876*0.957^(t/10), 0.438554']
PRED: '32' | GOLD: '32'
PRED: '32' | GOLD: '32'
PRED: '32' | GOLD: '32'
PRED: '32' | GOLD: '32'
PRED: '99756' | GOLD: '200000, 219'
PRED: '58' | GOLD: '200000, 219'
PRED: '66' | GOLD: '200000, 219'
PRED: '425000' | GOLD: '200000, 219'
PRED: '72' | GOLD: '60'
PRED: '28' | GOLD: '60'
PRED: '17' | GOLD: '60'
PRED: '34' | GOLD: '60'
PRED: '62' | GOLD: '     8000,        62'
PRED: '62' | GOLD: '     8000,        62'
PRED: '62' | GOLD: '     8000,        62'
PRED: '62' | GOLD: '     8000,        62'
PRED: '1. \\text{ Equivalent' | GOLD: 'EQUIVALENT, NOT EQUIVALENT, EQUIVALENT, Not Equiva'
PRED: '1. Y,\\ 2. Y,\\ 3. N,\\ 4. N,\\ 5. N' | GOLD: 'EQUIVALENT, NOT EQUIVALENT, EQUIVALENT, Not Equiva'
PRED: '4' | GOLD: 'EQUIVALENT, NOT EQUIVALENT, EQUIVALENT, Not Equiva'
PRED: '4' | GOLD: 'EQUIVALENT, NOT EQUIVALENT, EQUIVALENT, Not Equiva'
PRED: '8' | GOLD: '16, 8.00'
PRED: '16' | GOLD: '16, 8.00'
PRED: '16' | GOLD: '16, 8.00'
PRED: '16' | GOLD: '16, 8.00'
PRED: 'A' | GOLD: 'E'
PRED: 'D' | GOLD: 'E'
PRED: 'A' | GOLD: 'E'
PRED: 'C' | GOLD: 'E'
PRED: 'A' | GOLD: 'A'
PRED: 'D' | GOLD: 'A'
PRED: 'A' | GOLD: 'A'
PRED: 'E' | GOLD: 'A'
rewards: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0] | golds: ['32', '32', '32', '32', '200000, 219', '200000, 219', '200000, 219', '200000, 219', '60', '60', '60', '60', '     8000,        62', '     8000,        62', '     8000,        62', '     8000,        62', 'EQUIVALENT, NOT EQUIVALENT, EQUIVALENT, Not Equivalent, Not Equivalent', 'EQUIVALENT, NOT EQUIVALENT, EQUIVALENT, Not Equivalent, Not Equivalent', 'EQUIVALENT, NOT EQUIVALENT, EQUIVALENT, Not Equivalent, Not Equivalent', 'EQUIVALENT, NOT EQUIVALENT, EQUIVALENT, Not Equivalent, Not Equivalent', '16, 8.00', '16, 8.00', '16, 8.00', '16, 8.00', 'E', 'E', 'E', 'E', 'A', 'A', 'A', 'A']
PRED: '42' | GOLD: '1164'
PRED: '2 (234)^{6' | GOLD: '1164'
PRED: '0' | GOLD: '1164'
PRED: '0' | GOLD: '1164'
PRED: '219' | GOLD: '9, 9, 363, 218, 17'
PRED: '25' | GOLD: '9, 9, 363, 218, 17'
PRED: '1' | GOLD: '9, 9, 363, 218, 17'
PRED: '0' | GOLD: '9, 9, 363, 218, 17'
PRED: '3x^7' | GOLD: '5*k^4, 3*x^7'
PRED: '3x^7' | GOLD: '5*k^4, 3*x^7'
PRED: '3x^7' | GOLD: '5*k^4, 3*x^7'
PRED: '3x^7' | GOLD: '5*k^4, 3*x^7'
PRED: '25' | GOLD: '13, 18'
PRED: '37' | GOLD: '13, 18'
PRED: '41' | GOLD: '13, 18'
PRED: '21' | GOLD: '13, 18'
PRED: '86.7' | GOLD: '10*1.1583^t, 15.83'
PRED: '2.90' | GOLD: '10*1.1583^t, 15.83'
PRED: '2.6' | GOLD: '10*1.1583^t, 15.83'
PRED: '12.08' | GOLD: '10*1.1583^t, 15.83'
PRED: '6' | GOLD: '250, 6'
PRED: '6' | GOLD: '250, 6'
PRED: '6' | GOLD: '250, 6'
PRED: '250' | GOLD: '250, 6'
PRED: 'h(x) = \\csc x' | GOLD: '8*x^4+6*x, csc(x)'
PRED: 'g(x) = 8\\csc^{4' | GOLD: '8*x^4+6*x, csc(x)'
PRED: 'h\\left(x\\right) = \\csc \\left(x\\right)' | GOLD: '8*x^4+6*x, csc(x)'
PRED: 'h(x) = \\csc(x)' | GOLD: '8*x^4+6*x, csc(x)'
PRED: '3' | GOLD: 'C'
PRED: 'D' | GOLD: 'C'
PRED: 'A' | GOLD: 'C'
PRED: 'D' | GOLD: 'C'
rewards: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0] | golds: ['1164', '1164', '1164', '1164', '9, 9, 363, 218, 17', '9, 9, 363, 218, 17', '9, 9, 363, 218, 17', '9, 9, 363, 218, 17', '5*k^4, 3*x^7', '5*k^4, 3*x^7', '5*k^4, 3*x^7', '5*k^4, 3*x^7', '13, 18', '13, 18', '13, 18', '13, 18', '10*1.1583^t, 15.83', '10*1.1583^t, 15.83', '10*1.1583^t, 15.83', '10*1.1583^t, 15.83', '250, 6', '250, 6', '250, 6', '250, 6', '8*x^4+6*x, csc(x)', '8*x^4+6*x, csc(x)', '8*x^4+6*x, csc(x)', '8*x^4+6*x, csc(x)', 'C', 'C', 'C', 'C']
PRED: 'B' | GOLD: 'H'
PRED: 'Z' | GOLD: 'H'
PRED: 'C' | GOLD: 'H'
PRED: 'A' | GOLD: 'H'
PRED: '38' | GOLD: '38'
PRED: '38' | GOLD: '38'
PRED: '38' | GOLD: '38'
PRED: '38' | GOLD: '38'
PRED: '16' | GOLD: '6*e^(16*x), 6'
PRED: '6e^{16x' | GOLD: '6*e^(16*x), 6'
PRED: '1' | GOLD: '6*e^(16*x), 6'
PRED: '121' | GOLD: '6*e^(16*x), 6'
PRED: '0.00' | GOLD: '12.25 = 1.75*n, 7'
PRED: 'a), a\\,n=12.25/1.75,\\,n=7' | GOLD: '12.25 = 1.75*n, 7'
PRED: '7' | GOLD: '12.25 = 1.75*n, 7'
PRED: '7' | GOLD: '12.25 = 1.75*n, 7'
PRED: 'A' | GOLD: 'G'
PRED: '4' | GOLD: 'G'
PRED: 'D' | GOLD: 'G'
PRED: 'C' | GOLD: 'G'
PRED: 'D' | GOLD: 'F'
PRED: 'C' | GOLD: 'F'
PRED: 'D' | GOLD: 'F'
PRED: 'B' | GOLD: 'F'
PRED: 'the claimed goodness-of-fit distribution. B. There' | GOLD: '143.43119010619, 9.34840, B'
PRED: 'the claim that the distribution of crashes conform' | GOLD: '143.43119010619, 9.34840, B'
PRED: 'the original claim. B. There is sufficient evidenc' | GOLD: '143.43119010619, 9.34840, B'
PRED: 'the claim that the distribution of crashes conform' | GOLD: '143.43119010619, 9.34840, B'
PRED: 'A' | GOLD: 'A'
PRED: 'A' | GOLD: 'A'
PRED: 'D' | GOLD: 'A'
PRED: 'A' | GOLD: 'A'
rewards: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0] | golds: ['H', 'H', 'H', 'H', '38', '38', '38', '38', '6*e^(16*x), 6', '6*e^(16*x), 6', '6*e^(16*x), 6', '6*e^(16*x), 6', '12.25 = 1.75*n, 7', '12.25 = 1.75*n, 7', '12.25 = 1.75*n, 7', '12.25 = 1.75*n, 7', 'G', 'G', 'G', 'G', 'F', 'F', 'F', 'F', '143.43119010619, 9.34840, B', '143.43119010619, 9.34840, B', '143.43119010619, 9.34840, B', '143.43119010619, 9.34840, B', 'A', 'A', 'A', 'A']
PRED: '19' | GOLD: 'x + y = 43, 5.07 * x + 2.95 * y = 186.21, 28'
PRED: '17' | GOLD: 'x + y = 43, 5.07 * x + 2.95 * y = 186.21, 28'
PRED: '25' | GOLD: 'x + y = 43, 5.07 * x + 2.95 * y = 186.21, 28'
PRED: '65' | GOLD: 'x + y = 43, 5.07 * x + 2.95 * y = 186.21, 28'
PRED: 'C' | GOLD: 'A'
PRED: 'A' | GOLD: 'A'
PRED: 'C' | GOLD: 'A'
PRED: 'C' | GOLD: 'A'
PRED: '5 \\sqrt{7' | GOLD: '[sqrt(7)]/5'
PRED: '7/25' | GOLD: '[sqrt(7)]/5'
PRED: '5' | GOLD: '[sqrt(7)]/5'
PRED: '1/5 \\sqrt{7' | GOLD: '[sqrt(7)]/5'
PRED: 'C' | GOLD: 'C'
PRED: 'C' | GOLD: 'C'
PRED: 'C' | GOLD: 'C'
PRED: 'C' | GOLD: 'C'
PRED: '20' | GOLD: 'C'
PRED: 'C' | GOLD: 'C'
PRED: '20' | GOLD: 'C'
PRED: 'C' | GOLD: 'C'
PRED: 'no answer' | GOLD: 'DO NOT REJECT, REJECT, REJECT'
PRED: 'reject' | GOLD: 'DO NOT REJECT, REJECT, REJECT'
PRED: 'do \\, not \\, reject,bad \\ dilema,do \\, reject' | GOLD: 'DO NOT REJECT, REJECT, REJECT'
PRED: 'reject, do not reject, reject' | GOLD: 'DO NOT REJECT, REJECT, REJECT'
PRED: 'problem.' | GOLD: '429.4'
PRED: 'problem.' | GOLD: '429.4'
PRED: 'answer' | GOLD: '429.4'
PRED: 'problem.' | GOLD: '429.4'
PRED: 'B' | GOLD: 'G'
PRED: 'A' | GOLD: 'G'
PRED: 'B' | GOLD: 'G'
PRED: 'E' | GOLD: 'G'
rewards: [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0] | golds: ['x + y = 43, 5.07 * x + 2.95 * y = 186.21, 28', 'x + y = 43, 5.07 * x + 2.95 * y = 186.21, 28', 'x + y = 43, 5.07 * x + 2.95 * y = 186.21, 28', 'x + y = 43, 5.07 * x + 2.95 * y = 186.21, 28', 'A', 'A', 'A', 'A', '[sqrt(7)]/5', '[sqrt(7)]/5', '[sqrt(7)]/5', '[sqrt(7)]/5', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'DO NOT REJECT, REJECT, REJECT', 'DO NOT REJECT, REJECT, REJECT', 'DO NOT REJECT, REJECT, REJECT', 'DO NOT REJECT, REJECT, REJECT', '429.4', '429.4', '429.4', '429.4', 'G', 'G', 'G', 'G']
PRED: 'B' | GOLD: 'J'
PRED: 'C' | GOLD: 'J'
PRED: 'F' | GOLD: 'J'
PRED: 'A' | GOLD: 'J'
PRED: 'researchers recorded their scores on a personality' | GOLD: 'A, C'
PRED: 'researchers measured how many members of the runne' | GOLD: 'A, C'
PRED: 'researchers were interested in determining the eff' | GOLD: 'A, C'
PRED: 'study found that runners with longer running dista' | GOLD: 'A, C'
PRED: 'C' | GOLD: 'F'
PRED: 'A' | GOLD: 'F'
PRED: '5' | GOLD: 'F'
PRED: 'B' | GOLD: 'F'
PRED: 'capital is less than the national mean" is a [ANS]' | GOLD: 'A, C, A, A'
PRED: 'captial is less than the national mean" is a [ANS]' | GOLD: 'A, C, A, A'
PRED: 'capital is less than the national mean" is a [ANS]' | GOLD: 'A, C, A, A'
PRED: 'captial is less than the national mean" is a [ANS]' | GOLD: 'A, C, A, A'
PRED: '0.3' | GOLD: 'G'
PRED: 'D' | GOLD: 'G'
PRED: '0.3' | GOLD: 'G'
PRED: 'A' | GOLD: 'G'
PRED: '>' | GOLD: '12+20/4, >, (12+20)/4'
PRED: '>' | GOLD: '12+20/4, >, (12+20)/4'
PRED: '>' | GOLD: '12+20/4, >, (12+20)/4'
PRED: '>' | GOLD: '12+20/4, >, (12+20)/4'
PRED: 'D' | GOLD: 'A'
PRED: 'A' | GOLD: 'A'
PRED: 'C' | GOLD: 'A'
PRED: 'C' | GOLD: 'A'
PRED: '4' | GOLD: '8, 4'
PRED: '4' | GOLD: '8, 4'
PRED: '4' | GOLD: '8, 4'
PRED: '4' | GOLD: '8, 4'
rewards: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0] | golds: ['J', 'J', 'J', 'J', 'A, C', 'A, C', 'A, C', 'A, C', 'F', 'F', 'F', 'F', 'A, C, A, A', 'A, C, A, A', 'A, C, A, A', 'A, C, A, A', 'G', 'G', 'G', 'G', '12+20/4, >, (12+20)/4', '12+20/4, >, (12+20)/4', '12+20/4, >, (12+20)/4', '12+20/4, >, (12+20)/4', 'A', 'A', 'A', 'A', '8, 4', '8, 4', '8, 4', '8, 4']
PRED: 'C' | GOLD: 'I'
PRED: 'B' | GOLD: 'I'
PRED: 'D' | GOLD: 'I'
PRED: 'B' | GOLD: 'I'
PRED: '660' | GOLD: '1957.2, 660'
PRED: '663.76' | GOLD: '1957.2, 660'
PRED: '660' | GOLD: '1957.2, 660'
PRED: '1957.2' | GOLD: '1957.2, 660'
PRED: 'A' | GOLD: 'D'
PRED: 'B' | GOLD: 'D'
PRED: 'C' | GOLD: 'D'
PRED: 'A' | GOLD: 'D'
PRED: '24' | GOLD: '3/1=x/8, 24'
PRED: '24' | GOLD: '3/1=x/8, 24'
PRED: '24' | GOLD: '3/1=x/8, 24'
PRED: '24' | GOLD: '3/1=x/8, 24'
PRED: 'C' | GOLD: 'A'
PRED: 'C' | GOLD: 'A'
PRED: 'B' | GOLD: 'A'
PRED: 'C' | GOLD: 'A'
PRED: '1.07' | GOLD: '1.07'
PRED: '1.07' | GOLD: '1.07'
PRED: '1.07' | GOLD: '1.07'
PRED: '0.07' | GOLD: '1.07'
PRED: 'm+59' | GOLD: '59+m'
PRED: '59+m' | GOLD: '59+m'
PRED: '59+m' | GOLD: '59+m'
PRED: '59 + m' | GOLD: '59+m'
PRED: '6' | GOLD: '84'
PRED: '7π' | GOLD: '84'
PRED: '7' | GOLD: '84'
PRED: '21' | GOLD: '84'
rewards: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0] | golds: ['I', 'I', 'I', 'I', '1957.2, 660', '1957.2, 660', '1957.2, 660', '1957.2, 660', 'D', 'D', 'D', 'D', '3/1=x/8, 24', '3/1=x/8, 24', '3/1=x/8, 24', '3/1=x/8, 24', 'A', 'A', 'A', 'A', '1.07', '1.07', '1.07', '1.07', '59+m', '59+m', '59+m', '59+m', '84', '84', '84', '84']
PRED: 'A' | GOLD: 'C, A, A'
PRED: 'A' | GOLD: 'C, A, A'
PRED: 'A' | GOLD: 'C, A, A'
PRED: 'A' | GOLD: 'C, A, A'
PRED: 'B' | GOLD: 'G'
PRED: 'A' | GOLD: 'G'
PRED: 'A' | GOLD: 'G'
PRED: 'A' | GOLD: 'G'
PRED: '{43' | GOLD: '7.14285714285714, 0.714285714285714, 24.2857142857'
PRED: '34' | GOLD: '7.14285714285714, 0.714285714285714, 24.2857142857'
PRED: '46' | GOLD: '7.14285714285714, 0.714285714285714, 24.2857142857'
PRED: '34' | GOLD: '7.14285714285714, 0.714285714285714, 24.2857142857'
PRED: '21' | GOLD: '18'
PRED: '18' | GOLD: '18'
PRED: '18' | GOLD: '18'
PRED: '18' | GOLD: '18'
PRED: '5' | GOLD: '-0.203125, 4.890625, -4.0625'
PRED: '-\\frac{11}{8}' | GOLD: '-0.203125, 4.890625, -4.0625'
PRED: '2' | GOLD: '-0.203125, 4.890625, -4.0625'
PRED: '9.44' | GOLD: '-0.203125, 4.890625, -4.0625'
PRED: 'C' | GOLD: 'H'
PRED: 'A' | GOLD: 'H'
PRED: 'C' | GOLD: 'H'
PRED: 'A' | GOLD: 'H'
PRED: 'B' | GOLD: 'G'
PRED: 'C' | GOLD: 'G'
PRED: 'A' | GOLD: 'G'
PRED: '1' | GOLD: 'G'
PRED: '7000' | GOLD: '7000'
PRED: '7000' | GOLD: '7000'
PRED: '7000' | GOLD: '7000'
PRED: '7000' | GOLD: '7000'
rewards: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0] | golds: ['C, A, A', 'C, A, A', 'C, A, A', 'C, A, A', 'G', 'G', 'G', 'G', '7.14285714285714, 0.714285714285714, 24.2857142857143', '7.14285714285714, 0.714285714285714, 24.2857142857143', '7.14285714285714, 0.714285714285714, 24.2857142857143', '7.14285714285714, 0.714285714285714, 24.2857142857143', '18', '18', '18', '18', '-0.203125, 4.890625, -4.0625', '-0.203125, 4.890625, -4.0625', '-0.203125, 4.890625, -4.0625', '-0.203125, 4.890625, -4.0625', 'H', 'H', 'H', 'H', 'G', 'G', 'G', 'G', '7000', '7000', '7000', '7000']
PRED: '3.818' | GOLD: '240, 3.80482'
PRED: '120' | GOLD: '240, 3.80482'
PRED: '3.819' | GOLD: '240, 3.80482'
PRED: '3.81' | GOLD: '240, 3.80482'
PRED: 'A' | GOLD: 'C'
PRED: 'B' | GOLD: 'C'
PRED: 'A' | GOLD: 'C'
PRED: 'D' | GOLD: 'C'
PRED: 'A' | GOLD: 'B'
PRED: 'A' | GOLD: 'B'
PRED: 'A' | GOLD: 'B'
PRED: 'A' | GOLD: 'B'
PRED: 's-3' | GOLD: '8*(s-3), r-3'
PRED: '8r-3' | GOLD: '8*(s-3), r-3'
PRED: 'r-3' | GOLD: '8*(s-3), r-3'
PRED: '4(s - 3)' | GOLD: '8*(s-3), r-3'
PRED: 'D' | GOLD: 'C'
PRED: 'A' | GOLD: 'C'
PRED: 'A' | GOLD: 'C'
PRED: 'A' | GOLD: 'C'
PRED: '600' | GOLD: '707.142857142857'
PRED: '550' | GOLD: '707.142857142857'
PRED: '30' | GOLD: '707.142857142857'
PRED: '1225' | GOLD: '707.142857142857'
PRED: '500' | GOLD: '500'
PRED: '500' | GOLD: '500'
PRED: '500' | GOLD: '500'
PRED: '500' | GOLD: '500'
PRED: 'A' | GOLD: 'I'
PRED: 'D' | GOLD: 'I'
PRED: 'A' | GOLD: 'I'
PRED: 'D' | GOLD: 'I'
rewards: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0] | golds: ['240, 3.80482', '240, 3.80482', '240, 3.80482', '240, 3.80482', 'C', 'C', 'C', 'C', 'B', 'B', 'B', 'B', '8*(s-3), r-3', '8*(s-3), r-3', '8*(s-3), r-3', '8*(s-3), r-3', 'C', 'C', 'C', 'C', '707.142857142857', '707.142857142857', '707.142857142857', '707.142857142857', '500', '500', '500', '500', 'I', 'I', 'I', 'I']
PRED: 'A' | GOLD: 'E'
PRED: 'D' | GOLD: 'E'
PRED: 'B' | GOLD: 'E'
PRED: 'D' | GOLD: 'E'
PRED: 'the proportion of people who drink coffee regularl' | GOLD: 'A, C, DG, A, D, D'
PRED: 'the population proportion. What is the hypothesis?' | GOLD: 'A, C, DG, A, D, D'
PRED: 'the event that a person in UBC drinks coffee regul' | GOLD: 'A, C, DG, A, D, D'
PRED: 'the proportion of all UBC students that drink coff' | GOLD: 'A, C, DG, A, D, D'
PRED: 'h^{-1' | GOLD: '5*x/(1-8*x)'
PRED: 'h^{-1' | GOLD: '5*x/(1-8*x)'
PRED: 'h^{-1' | GOLD: '5*x/(1-8*x)'
PRED: 'h^{-1' | GOLD: '5*x/(1-8*x)'
PRED: ': ([ANS], [ANS]) Right vertex: ([ANS], [ANS]) Left' | GOLD: '0, 0, 9, 0, -9, 0, 0, 4, 0, -4, 8.06225774829855, '
PRED: ': ([ANS], [ANS]) Right vertex: ([ANS], [ANS]) Left' | GOLD: '0, 0, 9, 0, -9, 0, 0, 4, 0, -4, 8.06225774829855, '
PRED: ': ([ANS], [ANS]) Right vertex: ([ANS], [ANS]) Left' | GOLD: '0, 0, 9, 0, -9, 0, 0, 4, 0, -4, 8.06225774829855, '
PRED: ': ([ANS], [ANS]) Right vertex: ([ANS], [ANS]) Left' | GOLD: '0, 0, 9, 0, -9, 0, 0, 4, 0, -4, 8.06225774829855, '
PRED: '-\\sin(\\alpha) = -\\frac{2\\sqrt{14' | GOLD: '-0.831479419283098'
PRED: '-\\frac{\\sqrt{56' | GOLD: '-0.831479419283098'
PRED: '余弦' | GOLD: '-0.831479419283098'
PRED: '[-\\dfrac{2\\sqrt{11' | GOLD: '-0.831479419283098'
PRED: 'E=\\frac{3' | GOLD: 'B'
PRED: 'E' | GOLD: 'B'
PRED: 'D' | GOLD: 'B'
PRED: 'A' | GOLD: 'B'
PRED: '110' | GOLD: '110'
PRED: '110' | GOLD: '110'
PRED: '110' | GOLD: '110'
PRED: '110' | GOLD: '110'
PRED: ', 100, 120, 90, 110, 120, 100, 120, 90, 130, 110, ' | GOLD: '-2.26939, 2.31461, 3.15118, 3.67596, 0.930124, 5.6'
PRED: ', 110, 90, 90).\nThe explanatory variables are: fat' | GOLD: '-2.26939, 2.31461, 3.15118, 3.67596, 0.930124, 5.6'
PRED: ', 90) and the explanatory variables are: proteins=' | GOLD: '-2.26939, 2.31461, 3.15118, 3.67596, 0.930124, 5.6'
PRED: ', 120, 110, 110, 110, 110, 110, 120). The explanat' | GOLD: '-2.26939, 2.31461, 3.15118, 3.67596, 0.930124, 5.6'
rewards: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0] | golds: ['E', 'E', 'E', 'E', 'A, C, DG, A, D, D', 'A, C, DG, A, D, D', 'A, C, DG, A, D, D', 'A, C, DG, A, D, D', '5*x/(1-8*x)', '5*x/(1-8*x)', '5*x/(1-8*x)', '5*x/(1-8*x)', '0, 0, 9, 0, -9, 0, 0, 4, 0, -4, 8.06225774829855, 0, -8.06225774829855, 0, -7, 7, -3, 7, -11, 7, -7, 16, -7, -2, -7, 15.0622577482985, -7, -1.06225774829855, 6, 4, 10, 4, 2, 4, 6, 7, 6, 1, 8.64575131106459, 4, 3.35424868893541, 4', '0, 0, 9, 0, -9, 0, 0, 4, 0, -4, 8.06225774829855, 0, -8.06225774829855, 0, -7, 7, -3, 7, -11, 7, -7, 16, -7, -2, -7, 15.0622577482985, -7, -1.06225774829855, 6, 4, 10, 4, 2, 4, 6, 7, 6, 1, 8.64575131106459, 4, 3.35424868893541, 4', '0, 0, 9, 0, -9, 0, 0, 4, 0, -4, 8.06225774829855, 0, -8.06225774829855, 0, -7, 7, -3, 7, -11, 7, -7, 16, -7, -2, -7, 15.0622577482985, -7, -1.06225774829855, 6, 4, 10, 4, 2, 4, 6, 7, 6, 1, 8.64575131106459, 4, 3.35424868893541, 4', '0, 0, 9, 0, -9, 0, 0, 4, 0, -4, 8.06225774829855, 0, -8.06225774829855, 0, -7, 7, -3, 7, -11, 7, -7, 16, -7, -2, -7, 15.0622577482985, -7, -1.06225774829855, 6, 4, 10, 4, 2, 4, 6, 7, 6, 1, 8.64575131106459, 4, 3.35424868893541, 4', '-0.831479419283098', '-0.831479419283098', '-0.831479419283098', '-0.831479419283098', 'B', 'B', 'B', 'B', '110', '110', '110', '110', '-2.26939, 2.31461, 3.15118, 3.67596, 0.930124, 5.60856, 12', '-2.26939, 2.31461, 3.15118, 3.67596, 0.930124, 5.60856, 12', '-2.26939, 2.31461, 3.15118, 3.67596, 0.930124, 5.60856, 12', '-2.26939, 2.31461, 3.15118, 3.67596, 0.930124, 5.60856, 12']
PRED: 'We should reject the hypothesis because the sample' | GOLD: '30, (81.03, 84.41), C, B'
PRED: 'We should reject the hypothesis since the confiden' | GOLD: '30, (81.03, 84.41), C, B'
PRED: '' | GOLD: '30, (81.03, 84.41), C, B'
PRED: 'We should reject the hypothesis because the sample' | GOLD: '30, (81.03, 84.41), C, B'
PRED: '16' | GOLD: '16, (-10, 10)'
PRED: '10' | GOLD: '16, (-10, 10)'
PRED: '16, 10' | GOLD: '16, (-10, 10)'
PRED: '16' | GOLD: '16, (-10, 10)'
PRED: '9' | GOLD: '9'
PRED: '9' | GOLD: '9'
PRED: '6' | GOLD: '9'
PRED: '8' | GOLD: '9'
PRED: 'a random sample of size n. How large must n be bef' | GOLD: 'D, D, A'
PRED: 'a sample of size 17. The assumptions of the t proc' | GOLD: 'D, D, A'
PRED: 'data from a simple random sample (SRS). Is it vali' | GOLD: 'D, D, A'
PRED: 'the data from a random sample of adults. To be saf' | GOLD: 'D, D, A'
PRED: 'A' | GOLD: 'H'
PRED: 'B' | GOLD: 'H'
PRED: 'B' | GOLD: 'H'
PRED: 'D' | GOLD: 'H'
PRED: '0, 1, 1, 22.50 * n + 117.00,\\leq,60,22.50 * n + 11' | GOLD: '22.5*n+117, 1, 60-1, 18.5*n+58, 60'
PRED: '18.50n + 58' | GOLD: '22.5*n+117, 1, 60-1, 18.5*n+58, 60'

('./lora_adapters/lora_grpo/lora_grpov3/tokenizer_config.json',
 './lora_adapters/lora_grpo/lora_grpov3/chat_template.jinja',
 './lora_adapters/lora_grpo/lora_grpov3/tokenizer.json')

In [9]:
from peft import PeftModel

# Load base model fresh
model = AutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    trust_remote_code=True,
    quantization_config=bnb_config,
    device_map="auto",
)
model.gradient_checkpointing_enable()
model = prepare_model_for_kbit_training(model)

# Load the trained LoRA weights from your checkpoint
model = PeftModel.from_pretrained(
    model,
    "./lora_adapters/lora_grpo/checkpoints/checkpoint-1250",
    is_trainable=True,   # ← keep weights trainable for continued training
)

print("Loaded adapter from checkpoint-1250")
model.print_trainable_parameters()

grpo_trainer = GRPOTrainer(
    model=model,
    args=grpo_config,
    train_dataset=grpo_dataset,
    reward_funcs=math_accuracy_reward,
    callbacks=[ClearCacheCallback()],
)

# No resume_from_checkpoint — start fresh step counter on new dataset
grpo_trainer.train(resume_from_checkpoint="./lora_adapters/lora_grpo/checkpoints/checkpoint-50")

grpo_trainer.save_model("./lora_adapters/lora_grpo/lora_grpo_v2")
tokenizer.save_pretrained("./lora_adapters/lora_grpo/lora_grpo_v2")

Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]

Loaded adapter from checkpoint-1250
trainable params: 21,823,488 || all params: 4,044,291,584 || trainable%: 0.5396

The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None, 'pad_token_id': 151643}.
Could not estimate the number of tokens of the input, floating-point operations will not be computed

('./lora_adapters/lora_grpo/lora_grpo_v2/tokenizer_config.json',
 './lora_adapters/lora_grpo/lora_grpo_v2/special_tokens_map.json',
 './lora_adapters/lora_grpo/lora_grpo_v2/chat_template.jinja',
 './lora_adapters/lora_grpo/lora_grpo_v2/vocab.json',
 './lora_adapters/lora_grpo/lora_grpo_v2/merges.txt',
 './lora_adapters/lora_grpo/lora_grpo_v2/added_tokens.json',
 './lora_adapters/lora_grpo/lora_grpo_v2/tokenizer.json')

In [3]:
from transformers import AutoModelForCausalLM
from peft import PeftModel

# Load the core base model
base = AutoModelForCausalLM.from_pretrained(MODEL_ID, device_map="cpu")

# Load your SFT LoRA checkpoint folder
model = PeftModel.from_pretrained(base, "./lora_adapters/lora_adapter_openr1_fixed/lora_adapter_openr1_fixed", adapter_name="lora")

# Load your GRPO LoRA checkpoint folder
model.load_adapter("./lora_adapters/lora_grpo/lora_grpo_v2", adapter_name="grpo")

# Combine them using a linear weighted combination
model.add_weighted_adapter(
    adapters=["lora", "grpo"], 
    weights=[0.5, 0.5],             # Adjust ratio based on evaluation goals
    adapter_name="lora_grpo_combined",
    combination_type="linear"
)

# Save only the new combined LoRA configuration and weights
model.set_adapter("lora_grpo_combined")
model.save_pretrained("./lora_adapters/lora_grpo_combined")
print("Combined adapter saved successfully!")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/398 [00:00<?, ?it/s]

Combined adapter saved successfully!